// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxyservice$0 from "../proxy_service/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearHistories(): $CancellablePromise<void> {
    return $Call.ByID(2821877464);
}

export function DeleteHistory(key: string): $CancellablePromise<void> {
    return $Call.ByID(1278263496, key);
}

/**
 * ExportHAR exports a supported HBIN history.
 */
export function ExportHAR(request: $models.HARExportRequest): $CancellablePromise<proxyservice$0.HARWriteResult> {
    return $Call.ByID(2209319660, request);
}

export function GetHistory(key: string): $CancellablePromise<(proxyservice$0.TrafficEntry | null)[] | null> {
    return $Call.ByID(376138247, key);
}

export function GetHistoryTrafficBodyView(key: string, id: number): $CancellablePromise<proxyservice$0.TrafficBodyView | null> {
    return $Call.ByID(557338097, key, id);
}

export function ListHistoryKeys(): $CancellablePromise<(proxyservice$0.HistoryMetadata | null)[] | null> {
    return $Call.ByID(3378745645);
}

export function ResendRequest(key: string, id: number, cfg: proxyservice$0.ResendConfig): $CancellablePromise<proxyservice$0.ResendResult> {
    return $Call.ByID(4049675985, key, id, cfg);
}
