// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface HARExportRequest {
    "key": string;
    "path": string;
    "trafficIds"?: number[] | null;
}
