// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxyservice$0 from "../proxy_service/models.js";

export interface HARExportRequest {
    "key": string;
    "path": string;
    "trafficIds"?: number[] | null;
}

export interface HARImportRequest {
    "path": string;
}

export interface TrafficExportRequest {
    "key": string;
    "kind": proxyservice$0.TrafficExportKind;
    "path": string;
    "targetType": string;
    "trafficIds"?: number[] | null;
}
