import type { ShortcutCommand } from './types'

// Keep this catalog independent from component implementations. Business panes only
// register handlers for these stable command IDs.
export const shortcutCatalog = [
  {
    id: 'app.save',
    categoryKey: 'shortcuts.categories.application',
    labelKey: 'shortcuts.commands.app.save',
    defaultBinding: { modifiers: ['primary'], key: 's' },
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'allow',
    globalCapable: false,
  },
  {
    id: 'app.openSettings',
    categoryKey: 'shortcuts.categories.application',
    labelKey: 'shortcuts.commands.app.openSettings',
    defaultBinding: { modifiers: ['primary'], key: ',' },
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'block',
    globalCapable: false,
  },
  {
    id: 'app.showMainWindow',
    categoryKey: 'shortcuts.categories.application',
    labelKey: 'shortcuts.commands.app.showMainWindow',
    defaultBinding: null,
    defaultScope: 'global',
    modalPolicy: 'allow',
    editablePolicy: 'allow',
    globalCapable: true,
  },
  {
    id: 'capture.toggleProxy',
    categoryKey: 'shortcuts.categories.capture',
    labelKey: 'shortcuts.commands.capture.toggleProxy',
    defaultBinding: null,
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'block',
    globalCapable: true,
  },
  ...(['capture', 'category', 'apiCollection', 'pythonPlugins', 'memstats'] as const).map(
    (section, index) =>
      ({
        id: `workbench.${section}`,
        categoryKey: 'shortcuts.categories.workbench',
        labelKey: `shortcuts.commands.workbench.${section}`,
        defaultBinding: { modifiers: ['primary'], key: String(index + 1) },
        defaultScope: 'application',
        modalPolicy: 'block',
        editablePolicy: 'block',
        globalCapable: false,
      }) satisfies ShortcutCommand,
  ),
  {
    id: 'workspace.newHttpRequest',
    categoryKey: 'shortcuts.categories.workspace',
    labelKey: 'shortcuts.commands.workspace.newHttpRequest',
    defaultBinding: { modifiers: ['primary'], key: 'n' },
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'block',
    globalCapable: false,
  },
  {
    id: 'workspace.newWebSocketRequest',
    categoryKey: 'shortcuts.categories.workspace',
    labelKey: 'shortcuts.commands.workspace.newWebSocketRequest',
    defaultBinding: { modifiers: ['primary', 'shift'], key: 'n' },
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'block',
    globalCapable: false,
  },
  {
    id: 'workspace.closeTab',
    categoryKey: 'shortcuts.categories.workspace',
    labelKey: 'shortcuts.commands.workspace.closeTab',
    defaultBinding: { modifiers: ['primary'], key: 'w' },
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'block',
    globalCapable: false,
  },
  {
    id: 'workspace.nextTab',
    categoryKey: 'shortcuts.categories.workspace',
    labelKey: 'shortcuts.commands.workspace.nextTab',
    defaultBinding: { modifiers: ['control'], key: 'Tab' },
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'block',
    globalCapable: false,
  },
  {
    id: 'workspace.previousTab',
    categoryKey: 'shortcuts.categories.workspace',
    labelKey: 'shortcuts.commands.workspace.previousTab',
    defaultBinding: { modifiers: ['control', 'shift'], key: 'Tab' },
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'block',
    globalCapable: false,
  },
  {
    id: 'requestEditor.send',
    categoryKey: 'shortcuts.categories.requestEditor',
    labelKey: 'shortcuts.commands.requestEditor.send',
    defaultBinding: { modifiers: ['primary'], key: 'Enter' },
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'allow',
    globalCapable: false,
  },
  {
    id: 'capture.focusFilter',
    categoryKey: 'shortcuts.categories.capture',
    labelKey: 'shortcuts.commands.capture.focusFilter',
    defaultBinding: { modifiers: ['primary'], key: 'f' },
    defaultScope: 'application',
    modalPolicy: 'block',
    editablePolicy: 'block',
    globalCapable: false,
  },
  ...['capture.toggleSystemProxy', 'capture.clearTraffic'].map(
    (id) =>
      ({
        id,
        categoryKey: 'shortcuts.categories.capture',
        labelKey: `shortcuts.commands.${id}`,
        defaultBinding: null,
        defaultScope: 'application',
        modalPolicy: 'block',
        editablePolicy: 'block',
        globalCapable: false,
      }) satisfies ShortcutCommand,
  ),
] satisfies ShortcutCommand[]

export const shortcutCatalogById = new Map(shortcutCatalog.map((command) => [command.id, command]))
