// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CACertificateInfo {
    "certPath": string;
    "keyPath": string;
    "certExists": boolean;
    "keyExists": boolean;
    "validPair": boolean;
    "isCa": boolean;
    "subject": string;
    "issuer": string;
    "serialNumber": string;
    "notBeforeMicros": number;
    "notAfterMicros": number;
    "sha256Fingerprint": string;
    "error": string;
}

export interface CacheConfig {
    "bodyCacheThresholdBytes": number;
    "maxWsMessages": number;
}

export interface ClientCertConfig {
    "enabled": boolean;
    "hostname": string;
    "certPath": string;
    "keyPath": string;
}

export interface CommonConfig {
    "logLevel": string;
    "logDisabled": boolean;
    "appFontFamily": string;
    "codeFontFamily": string;
    "themeMode": string;
    "language": string;
}

export interface FontOption {
    "label": string;
    "value": string;
}

export interface GenerateCACertificateRequest {
    "overwrite": boolean;
    "commonName": string;
    "validDays": number;
}

export interface HistoryRetentionConfig {
    "enabled": boolean;
    "value": number;
    "unit": HistoryRetentionUnit;
}

export enum HistoryRetentionUnit {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    HistoryRetentionUnitHour = "hour",
    HistoryRetentionUnitDay = "day",
    HistoryRetentionUnitWeek = "week",
    HistoryRetentionUnitMonth = "month",
    HistoryRetentionUnitYear = "year",
};

export interface LocalIPAddress {
    "label": string;
    "value": string;
    "interfaceName"?: string;
}

export enum MainWindowCloseBehavior {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MainWindowCloseBehaviorHideToTray = "hide_to_tray",
    MainWindowCloseBehaviorQuit = "quit",
};

export interface ProcessAttributionConfig {
    "enabled": boolean;
}

export interface ProxyConfig {
    "mode": ProxyMode;
    "host": string;
    "port": number;
    "caCertPath": string;
    "caKeyPath": string;
    "upstreamProxyMode": UpstreamProxyMode;
    "upstreamProxy": string;
    "disableProxy": boolean;
    "disableHttp2": boolean;
    "skipVerifyTls": boolean;
    "includeHosts": string[] | null;
    "excludeHosts": string[] | null;
    "rootCAPaths": string[] | null;
    "clientCerts": ClientCertConfig[] | null;
}

export enum ProxyMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProxyModeHTTP = "http",
    ProxyModeSOCKS5 = "socks5",
};

export interface PythonPluginConfig {
    "enabled": boolean;
    "interpreterPath": string;
    "hookTimeoutMs": number;
}

export interface Settings {
    "commonConfig": CommonConfig | null;
    "proxyConfig": ProxyConfig | null;
    "windowConfig": WindowConfig | null;
    "cacheConfig": CacheConfig | null;
    "historyRetentionConfig": HistoryRetentionConfig | null;
    "processAttributionConfig": ProcessAttributionConfig | null;
    "trafficTableConfig": TrafficTableConfig | null;
    "pythonPluginConfig": PythonPluginConfig | null;
    "shortcuts": ShortcutConfig | null;
}

export interface ShortcutBinding {
    "modifiers": ShortcutModifier[] | null;
    "key": string;
}

export interface ShortcutConfig {
    "overrides": { [_ in string]?: ShortcutOverride } | null;
}

export enum ShortcutModifier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShortcutModifierPrimary = "primary",
    ShortcutModifierControl = "control",
    ShortcutModifierAlt = "alt",
    ShortcutModifierShift = "shift",
    ShortcutModifierSuper = "super",
};

export interface ShortcutOverride {
    /**
     * A nil Binding represents an explicit disabled shortcut.
     */
    "binding": ShortcutBinding | null;
    "scope": ShortcutScope;
}

export enum ShortcutScope {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShortcutScopeApplication = "application",
    ShortcutScopeGlobal = "global",
};

export interface TrafficTableConfig {
    "hiddenColumns": string[] | null;
}

export enum UpstreamProxyMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UpstreamProxyModeNone = "none",
    UpstreamProxyModeSystem = "system",
    UpstreamProxyModeCustom = "custom",
};

export interface WindowConfig {
    "positionX": number;
    "positionY": number;
    "width": number;
    "height": number;
    "hasPosition": boolean;
    "isMaximized": boolean;
    "isFullScreen": boolean;
    "frameMode": WindowFrameMode;
    "mainWindowCloseBehavior": MainWindowCloseBehavior;
}

export enum WindowFrameMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WindowFrameModeCustom = "custom",
    WindowFrameModeSystem = "system",
};
