// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GenerateCurrentCACertificate(req: $models.GenerateCACertificateRequest): $CancellablePromise<$models.CACertificateInfo | null> {
    return $Call.ByID(3510926544, req);
}

export function Get(): $CancellablePromise<$models.Settings | null> {
    return $Call.ByID(3875047717);
}

export function GetActiveWindowFrameMode(): $CancellablePromise<$models.WindowFrameMode> {
    return $Call.ByID(2660461815);
}

export function GetCACertificateInfo(): $CancellablePromise<$models.CACertificateInfo | null> {
    return $Call.ByID(2936179192);
}

export function GetProxyConfig(): $CancellablePromise<$models.ProxyConfig | null> {
    return $Call.ByID(2423391465);
}

export function GetWindowConfig(): $CancellablePromise<$models.WindowConfig | null> {
    return $Call.ByID(1736532847);
}

export function ListLocalIPv4Addresses(): $CancellablePromise<$models.LocalIPAddress[] | null> {
    return $Call.ByID(3222243543);
}

export function ListSystemFonts(): $CancellablePromise<$models.FontOption[] | null> {
    return $Call.ByID(3226482152);
}

export function Load(): $CancellablePromise<void> {
    return $Call.ByID(1518463851);
}

export function Save(): $CancellablePromise<void> {
    return $Call.ByID(2229573638);
}

/**
 * SaveTrafficTableConfig persists only the traffic_table section and updates
 * the in-memory snapshot after the database write succeeds. The persistence
 * mutex serializes this narrow database write with ordinary whole-settings Save
 * calls.
 */
export function SaveTrafficTableConfig(config: $models.TrafficTableConfig | null): $CancellablePromise<void> {
    return $Call.ByID(975328951, config);
}

export function SetLanguage(language: string): $CancellablePromise<void> {
    return $Call.ByID(3545568751, language);
}

export function SetThemeMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3404974341, mode);
}

/**
 * UpdatePreservingShortcuts replaces ordinary settings sections while retaining
 * the backend-latest shortcut and Python plugin runtime configurations. Both are
 * written through narrow services and must not be overwritten by a settings
 * window based on an older Get snapshot.
 */
export function UpdatePreservingShortcuts(settings: $models.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(1387277136, settings);
}

export function UpdateWindowConfig(windowConfig: $models.WindowConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3283140064, windowConfig);
}
