package proxyservice

import (
	"fmt"
	"net/url"
	"slices"
	"strconv"
	"strings"

	http "github.com/josexy/xhttp"
	"golang.org/x/net/http/httpguts"
)

func normalizeSendRequestProtocol(protocol SendRequestProtocol) (SendRequestProtocol, error) {
	switch protocol {
	case "", SendRequestProtocolAuto:
		return SendRequestProtocolAuto, nil
	case SendRequestProtocolHTTP1, SendRequestProtocolHTTP2:
		return protocol, nil
	default:
		return "", fmt.Errorf("unsupported HTTP request protocol: %s", protocol)
	}
}

func normalizeSyntheticHeaderFields(
	method string,
	targetURL *url.URL,
	protocol SendRequestProtocol,
	fields []HTTPHeaderField,
	generatedContentType string,
) ([]HTTPHeaderField, error) {
	normalized := make([]HTTPHeaderField, 0, len(fields)+4)
	for _, field := range fields {
		var include bool
		var err error
		field, include, err = normalizeUserRequestHeaderField(field)
		if err != nil {
			return nil, err
		}
		if !include {
			continue
		}
		normalized = append(normalized, field)
	}

	var err error
	switch protocol {
	case SendRequestProtocolAuto, SendRequestProtocolHTTP1:
		normalized, err = normalizeSyntheticHTTP1RouteFields(normalized, targetURL.Host)
	case SendRequestProtocolHTTP2:
		normalized, err = normalizeSyntheticHTTP2RouteFields(normalized, strings.ToUpper(method), targetURL)
	default:
		err = fmt.Errorf("unsupported HTTP request protocol: %s", protocol)
	}
	if err != nil {
		return nil, err
	}
	normalized = applySyntheticGeneratedContentType(normalized, generatedContentType, protocol)
	return normalized, nil
}

func normalizeUserRequestHeaderField(field HTTPHeaderField) (HTTPHeaderField, bool, error) {
	field.Name = strings.TrimSpace(field.Name)
	if field.Name == "" {
		return HTTPHeaderField{}, false, nil
	}
	if strings.HasPrefix(field.Name, ":") {
		return HTTPHeaderField{}, false, fmt.Errorf(
			"HTTP pseudo-header %q is generated by the backend and cannot be supplied",
			field.Name,
		)
	}
	if !httpguts.ValidHeaderFieldName(field.Name) {
		return HTTPHeaderField{}, false, fmt.Errorf("invalid HTTP header name %q", field.Name)
	}
	if !httpguts.ValidHeaderFieldValue(field.Value) {
		return HTTPHeaderField{}, false, fmt.Errorf("invalid value for HTTP header %q", field.Name)
	}
	return field, true, nil
}

func inferOrderedRequestProtocol(message *HTTPMessage) SendRequestProtocol {
	if message == nil || message.HeadersTruncated || message.HeaderOrderUnavailable || message.HeaderFields == nil {
		return SendRequestProtocolAuto
	}
	switch {
	case strings.HasPrefix(message.Proto, "HTTP/1"):
		return SendRequestProtocolHTTP1
	case strings.HasPrefix(message.Proto, "HTTP/2"):
		return SendRequestProtocolHTTP2
	default:
		return SendRequestProtocolAuto
	}
}

func ordinaryRequestHeaderFields(fields []HTTPHeaderField) []HTTPHeaderField {
	ordinary := make([]HTTPHeaderField, 0, len(fields))
	for _, field := range fields {
		if strings.HasPrefix(strings.TrimSpace(field.Name), ":") {
			continue
		}
		ordinary = append(ordinary, field)
	}
	return ordinary
}

func normalizeSyntheticHTTP1RouteFields(fields []HTTPHeaderField, authority string) ([]HTTPHeaderField, error) {
	hostIndex := -1
	for index := range fields {
		name := strings.ToLower(fields[index].Name)
		if name != "host" {
			continue
		}
		if hostIndex >= 0 {
			return nil, fmt.Errorf("HTTP request contains multiple Host fields")
		}
		hostIndex = index
		fields[index].Value = authority
	}
	if hostIndex >= 0 {
		return fields, nil
	}
	return append([]HTTPHeaderField{{Name: "Host", Value: authority}}, fields...), nil
}

func normalizeSyntheticHTTP2RouteFields(
	fields []HTTPHeaderField,
	method string,
	targetURL *url.URL,
) ([]HTTPHeaderField, error) {
	requestPath := targetURL.RequestURI()
	if requestPath == "" {
		requestPath = "/"
	}
	routeFields := []HTTPHeaderField{
		{Name: ":method", Value: method},
		{Name: ":authority", Value: targetURL.Host},
		{Name: ":scheme", Value: targetURL.Scheme},
		{Name: ":path", Value: requestPath},
	}
	if method == http.MethodConnect {
		routeFields = routeFields[:2]
	}

	hostSeen := false
	normalized := make([]HTTPHeaderField, 0, len(fields)+len(routeFields))
	normalized = append(normalized, routeFields...)
	for _, field := range fields {
		lowerName := strings.ToLower(field.Name)
		switch lowerName {
		case "host":
			if hostSeen {
				return nil, fmt.Errorf("HTTP request contains multiple Host fields")
			}
			hostSeen = true
			continue
		case "connection", "keep-alive", "proxy-connection", "transfer-encoding", "upgrade":
			return nil, fmt.Errorf("HTTP header %q is not valid in HTTP/2", field.Name)
		case "te":
			trimmedValue := strings.TrimSpace(field.Value)
			if trimmedValue != "" && !strings.EqualFold(trimmedValue, "trailers") {
				return nil, fmt.Errorf(`HTTP/2 header "te" may only be "trailers"`)
			}
			field.Value = strings.ToLower(trimmedValue)
		}
		field.Name = lowerName
		normalized = append(normalized, field)
	}
	return normalized, nil
}

func applySyntheticGeneratedContentType(
	fields []HTTPHeaderField,
	contentType string,
	protocol SendRequestProtocol,
) []HTTPHeaderField {
	if contentType == "" {
		return fields
	}
	result := make([]HTTPHeaderField, 0, len(fields)+1)
	found := false
	for _, field := range fields {
		if !strings.EqualFold(field.Name, "Content-Type") {
			result = append(result, field)
			continue
		}
		if found {
			continue
		}
		field.Value = contentType
		result = append(result, field)
		found = true
	}
	if !found {
		name := "Content-Type"
		if protocol == SendRequestProtocolHTTP2 {
			name = "content-type"
		}
		result = append(result, HTTPHeaderField{Name: name, Value: contentType})
	}
	return result
}

func reconcileSyntheticBodyFraming(
	fields []HTTPHeaderField,
	protocol SendRequestProtocol,
	contentLength int64,
	hasBody bool,
) []HTTPHeaderField {
	result := make([]HTTPHeaderField, 0, len(fields)+1)
	insertAt := -1
	contentLengthName := ""
	transferEncodingName := ""
	for _, field := range fields {
		switch strings.ToLower(field.Name) {
		case "content-length":
			if insertAt < 0 {
				insertAt = len(result)
			}
			if contentLengthName == "" {
				contentLengthName = field.Name
			}
		case "transfer-encoding":
			if insertAt < 0 {
				insertAt = len(result)
			}
			if transferEncodingName == "" {
				transferEncodingName = field.Name
			}
		default:
			result = append(result, field)
		}
	}

	if !hasBody {
		return result
	}
	if insertAt < 0 {
		insertAt = len(result)
	}

	var framing HTTPHeaderField
	if contentLength >= 0 {
		framing.Name = contentLengthName
		if framing.Name == "" {
			framing.Name = "Content-Length"
		}
		framing.Value = strconv.FormatInt(contentLength, 10)
	} else if protocol != SendRequestProtocolHTTP2 {
		framing.Name = transferEncodingName
		if framing.Name == "" {
			framing.Name = "Transfer-Encoding"
		}
		framing.Value = "chunked"
	} else {
		return result
	}
	if protocol == SendRequestProtocolHTTP2 {
		framing.Name = strings.ToLower(framing.Name)
	}

	result = append(result, HTTPHeaderField{})
	copy(result[insertAt+1:], result[insertAt:])
	result[insertAt] = framing
	return result
}

func validateSyntheticAutoHeaderOrder(fields []HTTPHeaderField) error {
	seenGroups := make(map[string]struct{}, len(fields))
	firstSpelling := make(map[string]string, len(fields))
	currentName := ""
	for _, field := range fields {
		lowerName := strings.ToLower(field.Name)
		if lowerName == "content-length" || lowerName == "transfer-encoding" {
			continue
		}
		if spelling, ok := firstSpelling[lowerName]; ok && spelling != field.Name {
			return fmt.Errorf(
				"automatic protocol selection cannot preserve per-occurrence casing for header %q; select HTTP/1.1 or HTTP/2",
				field.Name,
			)
		}
		firstSpelling[lowerName] = field.Name
		if lowerName == currentName {
			continue
		}
		if _, seen := seenGroups[lowerName]; seen {
			return fmt.Errorf(
				"automatic protocol selection cannot preserve interleaved occurrences of header %q; select HTTP/1.1 or HTTP/2",
				field.Name,
			)
		}
		seenGroups[lowerName] = struct{}{}
		currentName = lowerName
	}
	return nil
}

func applySyntheticHeaderFields(req *http.Request, fields []HTTPHeaderField) {
	for _, field := range fields {
		lowerName := strings.ToLower(field.Name)
		if strings.HasPrefix(lowerName, ":") || lowerName == "host" {
			continue
		}
		if lowerName == "content-length" || lowerName == "transfer-encoding" {
			continue
		}
		req.Header.Add(field.Name, field.Value)
	}
}

func applyFallbackUserAgentField(
	fields []HTTPHeaderField,
	protocol SendRequestProtocol,
) []HTTPHeaderField {
	emptyIndex := -1
	for index := range fields {
		if !strings.EqualFold(fields[index].Name, "User-Agent") {
			continue
		}
		if strings.TrimSpace(fields[index].Value) != "" {
			return fields
		}
		if emptyIndex < 0 {
			emptyIndex = index
		}
	}

	if emptyIndex >= 0 {
		fields[emptyIndex].Value = UserAgentHeader
		return fields
	}

	name := "User-Agent"
	if protocol == SendRequestProtocolHTTP2 {
		name = "user-agent"
	}
	return append(fields, HTTPHeaderField{Name: name, Value: UserAgentHeader})
}

func syntheticHeaderNameOrder(fields []HTTPHeaderField) []string {
	order := make([]string, 0, len(fields))
	seen := make(map[string]struct{}, len(fields))
	for _, field := range fields {
		lowerName := strings.ToLower(field.Name)
		if lowerName == "" || strings.HasPrefix(lowerName, ":") {
			continue
		}
		if _, ok := seen[lowerName]; ok {
			continue
		}
		seen[lowerName] = struct{}{}
		order = append(order, field.Name)
	}
	return order
}

func syntheticRequestHeaderBlock(protocol SendRequestProtocol, fields []HTTPHeaderField) http.HeaderBlock {
	protoMajor := 1
	if protocol == SendRequestProtocolHTTP2 {
		protoMajor = 2
	}
	block := http.HeaderBlock{
		Kind:       http.HeaderBlockInitial,
		ProtoMajor: protoMajor,
		Fields:     make([]http.HeaderField, len(fields)),
	}
	for index, field := range fields {
		block.Fields[index] = http.HeaderField{Name: field.Name, Value: field.Value}
	}
	return block
}

func syntheticFingerprintRequestHeaderBlock(
	fields []HTTPHeaderField,
	pseudoHeaderOrder []string,
) http.HeaderBlock {
	block := http.HeaderBlock{
		Kind:       http.HeaderBlockInitial,
		ProtoMajor: 2,
		Fields:     make([]http.HeaderField, 0, len(fields)),
	}
	pseudoFields := make(map[string]HTTPHeaderField, len(pseudoHeaderOrder))
	for _, field := range fields {
		if strings.HasPrefix(field.Name, ":") {
			pseudoFields[field.Name] = field
		}
	}
	for _, name := range pseudoHeaderOrder {
		if field, ok := pseudoFields[name]; ok {
			block.Fields = append(block.Fields, http.HeaderField{Name: field.Name, Value: field.Value})
		}
	}
	for _, field := range fields {
		if strings.HasPrefix(field.Name, ":") {
			continue
		}
		block.Fields = append(block.Fields, http.HeaderField{Name: field.Name, Value: field.Value})
	}
	return block
}

func rebuildSyntheticHTTP2FingerprintRedirectRequest(
	req *http.Request,
	template []HTTPHeaderField,
	fingerprint *http.Fingerprint,
) (*http.Request, error) {
	if req == nil || req.URL == nil {
		return nil, fmt.Errorf("HTTP/2 redirect request URL is required")
	}
	if fingerprint == nil {
		return nil, fmt.Errorf("HTTP/2 redirect fingerprint is required")
	}
	if err := normalizeSyntheticURLHostname(req.URL); err != nil {
		return nil, err
	}

	valuesByName := make(map[string][]string, len(req.Header))
	for name, values := range req.Header {
		lowerName := strings.ToLower(name)
		valuesByName[lowerName] = append(valuesByName[lowerName], values...)
	}

	fields := make([]HTTPHeaderField, 0, len(req.Header)+4)
	appendHeader := func(lowerName string) {
		values, ok := valuesByName[lowerName]
		if !ok {
			return
		}
		delete(valuesByName, lowerName)
		for _, value := range values {
			fields = append(fields, HTTPHeaderField{Name: lowerName, Value: value})
		}
	}
	for _, field := range template {
		lowerName := strings.ToLower(field.Name)
		switch {
		case lowerName == "", strings.HasPrefix(lowerName, ":"), lowerName == "host":
			continue
		case lowerName == "content-length":
			if req.Body != nil && req.ContentLength >= 0 {
				fields = append(fields, HTTPHeaderField{
					Name:  lowerName,
					Value: strconv.FormatInt(req.ContentLength, 10),
				})
			}
			delete(valuesByName, lowerName)
		default:
			appendHeader(lowerName)
		}
	}

	remainingNames := make([]string, 0, len(valuesByName))
	for lowerName := range valuesByName {
		if lowerName == "host" || lowerName == "content-length" || lowerName == "transfer-encoding" {
			continue
		}
		remainingNames = append(remainingNames, lowerName)
	}
	slices.Sort(remainingNames)
	for _, lowerName := range remainingNames {
		appendHeader(lowerName)
	}

	fields, err := normalizeSyntheticHTTP2RouteFields(fields, strings.ToUpper(req.Method), req.URL)
	if err != nil {
		return nil, err
	}
	fields = reconcileSyntheticBodyFraming(
		fields,
		SendRequestProtocolHTTP2,
		req.ContentLength,
		req.Body != nil,
	)
	fields = applyFallbackUserAgentField(fields, SendRequestProtocolHTTP2)
	return http.WithRequestHeaderBlocks(
		req,
		syntheticFingerprintRequestHeaderBlock(fields, fingerprint.PseudoHeaderOrder),
		nil,
	)
}

func isSOCKSProxyURL(proxyURL *url.URL) bool {
	if proxyURL == nil {
		return false
	}
	switch strings.ToLower(proxyURL.Scheme) {
	case "socks5", "socks5h":
		return true
	default:
		return false
	}
}
