package proxyservice

import (
	"bufio"
	"context"
	"io"
	"net"
	"net/url"
	"reflect"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	settingservice "github.com/josexy/flowlens/backend/services/setting_service"
	http "github.com/josexy/xhttp"
	"github.com/josexy/xhttp/httptest"
)

func TestNormalizeSyntheticHeaderFieldsRoutesAndContentType(t *testing.T) {
	target, err := url.Parse("https://new.test:8443/path?q=1")
	if err != nil {
		t.Fatal(err)
	}
	fields := []HTTPHeaderField{
		{Name: "X-First", Value: "one"},
		{Name: "hOsT", Value: "old.test"},
		{Name: "cOnTeNt-TyPe", Value: "old"},
		{Name: "X-Second", Value: "two"},
		{Name: "Content-Type", Value: "duplicate"},
	}
	got, err := normalizeSyntheticHeaderFields("POST", target, SendRequestProtocolHTTP1, fields, "application/json")
	if err != nil {
		t.Fatal(err)
	}
	want := []HTTPHeaderField{
		{Name: "X-First", Value: "one"},
		{Name: "hOsT", Value: "new.test:8443"},
		{Name: "cOnTeNt-TyPe", Value: "application/json"},
		{Name: "X-Second", Value: "two"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("normalized fields:\n got %#v\nwant %#v", got, want)
	}
}

func TestNormalizeSyntheticHTTP2RouteFields(t *testing.T) {
	target, _ := url.Parse("https://new.test/path?q=1")
	fields := []HTTPHeaderField{
		{Name: "X-A", Value: "one"},
	}
	got, err := normalizeSyntheticHeaderFields("POST", target, SendRequestProtocolHTTP2, fields, "application/json")
	if err != nil {
		t.Fatal(err)
	}
	want := []HTTPHeaderField{
		{Name: ":method", Value: "POST"},
		{Name: ":authority", Value: "new.test"},
		{Name: ":scheme", Value: "https"},
		{Name: ":path", Value: "/path?q=1"},
		{Name: "x-a", Value: "one"},
		{Name: "content-type", Value: "application/json"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("HTTP/2 route fields:\n got %#v\nwant %#v", got, want)
	}

	connect, err := normalizeSyntheticHeaderFields("CONNECT", target, SendRequestProtocolHTTP2, []HTTPHeaderField{
		{Name: "x-a", Value: "one"},
	}, "")
	if err != nil {
		t.Fatal(err)
	}
	wantConnect := []HTTPHeaderField{
		{Name: ":method", Value: "CONNECT"},
		{Name: ":authority", Value: "new.test"},
		{Name: "x-a", Value: "one"},
	}
	if !reflect.DeepEqual(connect, wantConnect) {
		t.Fatalf("CONNECT route fields:\n got %#v\nwant %#v", connect, wantConnect)
	}
}

func TestNormalizeSyntheticHeaderFieldsRejectsInvalidControlledRows(t *testing.T) {
	target, _ := url.Parse("https://example.test/")
	tests := []struct {
		name     string
		protocol SendRequestProtocol
		fields   []HTTPHeaderField
		want     string
	}{
		{
			name:     "duplicate host",
			protocol: SendRequestProtocolHTTP1,
			fields:   []HTTPHeaderField{{Name: "Host"}, {Name: "host"}},
			want:     "multiple Host",
		},
		{
			name:     "request pseudo",
			protocol: SendRequestProtocolHTTP2,
			fields:   []HTTPHeaderField{{Name: ":method"}},
			want:     "generated by the backend",
		},
		{
			name:     "response pseudo",
			protocol: SendRequestProtocolHTTP2,
			fields:   []HTTPHeaderField{{Name: ":status", Value: "200"}},
			want:     "generated by the backend",
		},
		{
			name:     "pseudo in HTTP1",
			protocol: SendRequestProtocolHTTP1,
			fields:   []HTTPHeaderField{{Name: ":method"}},
			want:     "generated by the backend",
		},
		{
			name:     "invalid token name",
			protocol: SendRequestProtocolHTTP1,
			fields:   []HTTPHeaderField{{Name: "Bad Header"}},
			want:     "invalid HTTP header name",
		},
		{
			name:     "invalid value",
			protocol: SendRequestProtocolHTTP1,
			fields:   []HTTPHeaderField{{Name: "X-Test", Value: "one\r\ntwo"}},
			want:     "invalid value",
		},
		{
			name:     "HTTP2 connection field",
			protocol: SendRequestProtocolHTTP2,
			fields:   []HTTPHeaderField{{Name: "Connection", Value: "keep-alive"}},
			want:     "not valid in HTTP/2",
		},
		{
			name:     "HTTP2 invalid TE",
			protocol: SendRequestProtocolHTTP2,
			fields:   []HTTPHeaderField{{Name: "TE", Value: "gzip"}},
			want:     `may only be "trailers"`,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := normalizeSyntheticHeaderFields("GET", target, test.protocol, test.fields, "")
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("error = %v, want substring %q", err, test.want)
			}
		})
	}
}

func TestSyntheticAutoGroupsNamesByFirstAppearance(t *testing.T) {
	fields := []HTTPHeaderField{
		{Name: "A", Value: "first"},
		{Name: "B", Value: "middle"},
		{Name: "a", Value: "last"},
	}
	if got, want := syntheticHeaderNameOrder(fields), []string{"A", "B"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("header name order = %#v, want %#v", got, want)
	}
}

func TestReconcileSyntheticBodyFraming(t *testing.T) {
	fields := []HTTPHeaderField{
		{Name: "X-Before", Value: "one"},
		{Name: "cOnTeNt-LeNgTh", Value: "999"},
		{Name: "X-Middle", Value: "two"},
		{Name: "Transfer-Encoding", Value: "gzip"},
		{Name: "X-After", Value: "three"},
	}
	tests := []struct {
		name          string
		protocol      SendRequestProtocol
		contentLength int64
		hasBody       bool
		want          []HTTPHeaderField
	}{
		{
			name:          "HTTP1 fixed length",
			protocol:      SendRequestProtocolHTTP1,
			contentLength: 4,
			hasBody:       true,
			want: []HTTPHeaderField{
				{Name: "X-Before", Value: "one"},
				{Name: "cOnTeNt-LeNgTh", Value: "4"},
				{Name: "X-Middle", Value: "two"},
				{Name: "X-After", Value: "three"},
			},
		},
		{
			name:          "HTTP1 streaming",
			protocol:      SendRequestProtocolHTTP1,
			contentLength: -1,
			hasBody:       true,
			want: []HTTPHeaderField{
				{Name: "X-Before", Value: "one"},
				{Name: "Transfer-Encoding", Value: "chunked"},
				{Name: "X-Middle", Value: "two"},
				{Name: "X-After", Value: "three"},
			},
		},
		{
			name:          "HTTP2 fixed length",
			protocol:      SendRequestProtocolHTTP2,
			contentLength: 4,
			hasBody:       true,
			want: []HTTPHeaderField{
				{Name: "X-Before", Value: "one"},
				{Name: "content-length", Value: "4"},
				{Name: "X-Middle", Value: "two"},
				{Name: "X-After", Value: "three"},
			},
		},
		{
			name:          "HTTP2 streaming",
			protocol:      SendRequestProtocolHTTP2,
			contentLength: -1,
			hasBody:       true,
			want: []HTTPHeaderField{
				{Name: "X-Before", Value: "one"},
				{Name: "X-Middle", Value: "two"},
				{Name: "X-After", Value: "three"},
			},
		},
		{
			name:          "no body",
			protocol:      SendRequestProtocolHTTP1,
			contentLength: 0,
			hasBody:       false,
			want: []HTTPHeaderField{
				{Name: "X-Before", Value: "one"},
				{Name: "X-Middle", Value: "two"},
				{Name: "X-After", Value: "three"},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := reconcileSyntheticBodyFraming(fields, tt.protocol, tt.contentLength, tt.hasBody)
			if !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("framing fields:\n got %#v\nwant %#v", got, tt.want)
			}
		})
	}
}

func TestApplyFallbackUserAgentField(t *testing.T) {
	tests := []struct {
		name     string
		protocol SendRequestProtocol
		fields   []HTTPHeaderField
		want     []HTTPHeaderField
	}{
		{
			name:     "HTTP1 missing",
			protocol: SendRequestProtocolHTTP1,
			fields:   []HTTPHeaderField{{Name: "X-Test", Value: "value"}},
			want: []HTTPHeaderField{
				{Name: "X-Test", Value: "value"},
				{Name: "User-Agent", Value: UserAgentHeader},
			},
		},
		{
			name:     "HTTP2 missing",
			protocol: SendRequestProtocolHTTP2,
			want:     []HTTPHeaderField{{Name: "user-agent", Value: UserAgentHeader}},
		},
		{
			name:     "explicit value",
			protocol: SendRequestProtocolHTTP1,
			fields:   []HTTPHeaderField{{Name: "user-agent", Value: "custom-agent"}},
			want:     []HTTPHeaderField{{Name: "user-agent", Value: "custom-agent"}},
		},
		{
			name:     "blank value",
			protocol: SendRequestProtocolHTTP1,
			fields:   []HTTPHeaderField{{Name: "USER-AGENT", Value: "  "}},
			want:     []HTTPHeaderField{{Name: "USER-AGENT", Value: UserAgentHeader}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := applyFallbackUserAgentField(tt.fields, tt.protocol)
			if !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("header fields:\n got %#v\nwant %#v", got, tt.want)
			}
		})
	}
}

func TestSendHTTPRequestHTTP1WritesExactHeaderLines(t *testing.T) {
	serverURL, wireCh := startRawHTTP1CaptureServer(t, "HTTP/1.1 200 OK\r\nX-R: first\r\nY: middle\r\nX-R: last\r\nContent-Length: 2\r\n\r\nok")
	svc := newTestProxyService(t, &settingservice.ProxyConfig{})
	response, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolHTTP1},
		http.MethodGet,
		serverURL+"/exact",
		[]HTTPHeaderField{
			{Name: "x-B", Value: "one"},
			{Name: "hOsT", Value: "wrong.test"},
			{Name: "x-A", Value: "two"},
			{Name: "X-B", Value: "three"},
		},
		SendRequestBody{BodyType: SendRequestBodyTypeNone},
	)
	if err != nil {
		t.Fatal(err)
	}
	wire := <-wireCh
	wantLines := []string{
		"x-B: one",
		"hOsT: " + strings.TrimPrefix(serverURL, "http://"),
		"x-A: two",
		"X-B: three",
		"User-Agent: " + UserAgentHeader,
	}
	if got := requestHeaderLines(wire); !reflect.DeepEqual(got, wantLines) {
		t.Fatalf("request header lines:\n got %#v\nwant %#v\nwire=%q", got, wantLines, wire)
	}
	wantResponseFields := []HTTPHeaderField{
		{Name: "X-R", Value: "first"},
		{Name: "Y", Value: "middle"},
		{Name: "X-R", Value: "last"},
		{Name: "Content-Length", Value: "2"},
	}
	if !reflect.DeepEqual(response.HeaderFields, wantResponseFields) {
		t.Fatalf("response fields:\n got %#v\nwant %#v", response.HeaderFields, wantResponseFields)
	}
}

func TestSendHTTPRequestAutoRejectsInterleavedDuplicateNames(t *testing.T) {
	svc := newTestProxyService(t, &settingservice.ProxyConfig{})
	_, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolAuto},
		http.MethodGet,
		"http://127.0.0.1:1/auto",
		[]HTTPHeaderField{
			{Name: "A", Value: "first"},
			{Name: "B", Value: "middle"},
			{Name: "A", Value: "last"},
		},
		SendRequestBody{BodyType: SendRequestBodyTypeNone},
	)
	if err == nil || !strings.Contains(err.Error(), "cannot preserve interleaved") {
		t.Fatalf("error = %v, want an exact-order guidance error", err)
	}
}

func TestSendHTTPRequestHTTP2WritesExactHeaderBlock(t *testing.T) {
	requestBlocks := make(chan []http.HeaderBlock, 1)
	server := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestBlocks <- http.RequestHeaderBlocks(r)
		w.WriteHeader(http.StatusNoContent)
	}))
	server.EnableHTTP2 = true
	server.StartTLS()
	defer server.Close()

	svc := newTestProxyService(t, &settingservice.ProxyConfig{SkipVerifyTLS: true})
	response, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolHTTP2},
		http.MethodGet,
		server.URL+"/h2?q=1",
		[]HTTPHeaderField{
			{Name: "X-A", Value: "first"},
			{Name: "X-B", Value: "middle"},
			{Name: "X-A", Value: "last"},
		},
		SendRequestBody{BodyType: SendRequestBodyTypeNone},
	)
	if err != nil {
		t.Fatal(err)
	}
	if response.Protocol != "HTTP/2.0" {
		t.Fatalf("response protocol = %q, want HTTP/2.0", response.Protocol)
	}
	if len(response.HeaderFields) == 0 || response.HeaderFields[0] != (HTTPHeaderField{Name: ":status", Value: "204"}) {
		t.Fatalf("HTTP/2 response fields = %#v, want leading :status", response.HeaderFields)
	}
	blocks := <-requestBlocks
	if len(blocks) == 0 {
		t.Fatal("server captured no HTTP/2 request HeaderBlock")
	}
	want := []http.HeaderField{
		{Name: ":method", Value: "GET"},
		{Name: ":authority", Value: strings.TrimPrefix(server.URL, "https://")},
		{Name: ":scheme", Value: "https"},
		{Name: ":path", Value: "/h2?q=1"},
		{Name: "x-a", Value: "first"},
		{Name: "x-b", Value: "middle"},
		{Name: "x-a", Value: "last"},
		{Name: "user-agent", Value: UserAgentHeader},
	}
	if !reflect.DeepEqual(blocks[0].Fields, want) {
		t.Fatalf("HTTP/2 request fields:\n got %#v\nwant %#v", blocks[0].Fields, want)
	}
}

func TestSendHTTPRequestHTTP2RegeneratesBodyMetadata(t *testing.T) {
	requestBlocks := make(chan []http.HeaderBlock, 1)
	server := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, err := io.ReadAll(r.Body)
		if err != nil {
			t.Errorf("read body: %v", err)
			return
		}
		if got := string(body); got != "body" {
			t.Errorf("body = %q, want body", got)
		}
		requestBlocks <- http.RequestHeaderBlocks(r)
		w.WriteHeader(http.StatusNoContent)
	}))
	server.EnableHTTP2 = true
	server.StartTLS()
	defer server.Close()

	svc := newTestProxyService(t, &settingservice.ProxyConfig{SkipVerifyTLS: true})
	_, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolHTTP2},
		http.MethodPost,
		server.URL+"/body",
		[]HTTPHeaderField{{Name: "Content-Length", Value: "999"}},
		SendRequestBody{BodyType: SendRequestBodyTypeText, Text: "body"},
	)
	if err != nil {
		t.Fatal(err)
	}
	blocks := <-requestBlocks
	if len(blocks) == 0 {
		t.Fatal("server captured no HTTP/2 request HeaderBlock")
	}
	wantTail := []http.HeaderField{
		{Name: "content-length", Value: "4"},
		{Name: "content-type", Value: "text/plain; charset=utf-8"},
		{Name: "user-agent", Value: UserAgentHeader},
	}
	if got := blocks[0].Fields[len(blocks[0].Fields)-len(wantTail):]; !reflect.DeepEqual(got, wantTail) {
		t.Fatalf("HTTP/2 body fields:\n got %#v\nwant %#v", got, wantTail)
	}
}

func TestSendHTTPRequestExplicitProtocolFollowsRedirect(t *testing.T) {
	var followed atomic.Bool
	target := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		followed.Store(true)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer target.Close()
	redirect := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Location", target.URL)
		w.WriteHeader(http.StatusFound)
	}))
	defer redirect.Close()

	svc := newTestProxyService(t, &settingservice.ProxyConfig{})
	response, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolHTTP1},
		http.MethodGet,
		redirect.URL,
		nil,
		SendRequestBody{BodyType: SendRequestBodyTypeNone},
	)
	if err != nil {
		t.Fatal(err)
	}
	if response.StatusCode != http.StatusNoContent || !followed.Load() {
		t.Fatalf("redirect response=%d followed=%v", response.StatusCode, followed.Load())
	}
}

func TestSendHTTPRequestExplicitHTTP1GeneratesContentLength(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, err := io.ReadAll(r.Body)
		if err != nil {
			t.Errorf("read body: %v", err)
			return
		}
		if got := string(body); got != "body" {
			t.Errorf("body = %q, want body", got)
		}
		if r.ContentLength != 4 {
			t.Errorf("ContentLength = %d, want 4", r.ContentLength)
		}
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	svc := newTestProxyService(t, &settingservice.ProxyConfig{})
	response, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolHTTP1},
		http.MethodPost,
		server.URL,
		nil,
		SendRequestBody{BodyType: SendRequestBodyTypeText, Text: "body"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if response.StatusCode != http.StatusNoContent {
		t.Fatalf("status = %d, want 204", response.StatusCode)
	}
}

func TestSendHTTPRequestExplicitHTTP1ReplacesStaleContentLength(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, err := io.ReadAll(r.Body)
		if err != nil {
			t.Errorf("read body: %v", err)
			return
		}
		if string(body) != "body" || r.ContentLength != 4 {
			t.Errorf("body=%q contentLength=%d", body, r.ContentLength)
		}
		if got := r.Header.Get("Content-Type"); got != "text/plain; charset=utf-8" {
			t.Errorf("Content-Type = %q", got)
		}
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	svc := newTestProxyService(t, &settingservice.ProxyConfig{})
	response, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolHTTP1},
		http.MethodPost,
		server.URL,
		[]HTTPHeaderField{{Name: "Content-Length", Value: "999"}},
		SendRequestBody{BodyType: SendRequestBodyTypeText, Text: "body"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if response.StatusCode != http.StatusNoContent {
		t.Fatalf("status = %d, want 204", response.StatusCode)
	}
}

func TestSendHTTPRequestExplicitHTTP1UpdatesMultipartBoundaryInPlace(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(1 << 20); err != nil {
			t.Errorf("ParseMultipartForm: %v", err)
			return
		}
		if got := r.FormValue("name"); got != "value" {
			t.Errorf("form value = %q", got)
		}
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	svc := newTestProxyService(t, &settingservice.ProxyConfig{})
	response, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolHTTP1},
		http.MethodPost,
		server.URL,
		[]HTTPHeaderField{
			{Name: "Content-Length", Value: "999"},
			{Name: "cOnTeNt-TyPe", Value: "multipart/form-data; boundary=stale"},
			{Name: "Content-Type", Value: "duplicate"},
		},
		SendRequestBody{
			BodyType: SendRequestBodyTypeFormData,
			FormData: []*SendRequestFormDataItem{{
				Enabled:  true,
				Name:     "name",
				ItemType: "text",
				Value:    "value",
			}},
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if response.StatusCode != http.StatusNoContent {
		t.Fatalf("status = %d, want 204", response.StatusCode)
	}
}

func TestSendHTTPRequestHTTP2H2CRejectsForwardProxy(t *testing.T) {
	svc := newTestProxyService(t, &settingservice.ProxyConfig{})
	_, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{
			ProxyMode:   SendRequestProxyModeCustom,
			Protocol:    SendRequestProtocolHTTP2,
			CustomProxy: "http://127.0.0.1:8080",
		},
		http.MethodGet,
		"http://example.test/",
		nil,
		SendRequestBody{BodyType: SendRequestBodyTypeNone},
	)
	if err == nil || !strings.Contains(err.Error(), "do not support HTTP forward proxies") {
		t.Fatalf("error = %v, want h2c proxy restriction", err)
	}
}

func TestSendHTTPRequestHTTP2UsesPriorKnowledgeH2CForDirectRequests(t *testing.T) {
	requestProto := make(chan string, 1)
	server := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestProto <- r.Proto
		w.WriteHeader(http.StatusNoContent)
	}))
	protocols := new(http.Protocols)
	protocols.SetUnencryptedHTTP2(true)
	server.Config.Protocols = protocols
	server.Start()
	defer server.Close()

	svc := newTestProxyService(t, &settingservice.ProxyConfig{})
	response, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolHTTP2},
		http.MethodGet,
		server.URL+"/h2c",
		nil,
		SendRequestBody{BodyType: SendRequestBodyTypeNone},
	)
	if err != nil {
		t.Fatal(err)
	}
	if response.Protocol != "HTTP/2.0" || <-requestProto != "HTTP/2.0" {
		t.Fatalf("h2c protocols: response=%q", response.Protocol)
	}
}

func TestSendHTTPRequestHTTP2DoesNotDowngradeToHTTP1(t *testing.T) {
	var called atomic.Bool
	server := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		called.Store(true)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	svc := newTestProxyService(t, &settingservice.ProxyConfig{SkipVerifyTLS: true})
	_, err := svc.SendHTTPRequest(
		context.Background(),
		SendRequestConfig{ProxyMode: SendRequestProxyModeNone, Protocol: SendRequestProtocolHTTP2},
		http.MethodGet,
		server.URL,
		nil,
		SendRequestBody{BodyType: SendRequestBodyTypeNone},
	)
	if err == nil {
		t.Fatal("explicit HTTP/2 unexpectedly downgraded to HTTP/1")
	}
	if called.Load() {
		t.Fatal("HTTP/1 handler ran for explicit HTTP/2 request")
	}
}

func TestResendRequestPreservesExactHTTP1HeaderOccurrences(t *testing.T) {
	serverURL, wireCh := startRawHTTP1CaptureServer(t, "HTTP/1.1 204 No Content\r\n\r\n")
	svc := newTestProxyService(t, &settingservice.ProxyConfig{})
	entry := &TrafficEntry{
		ID:     301,
		Type:   "http",
		Method: http.MethodGet,
		URL:    serverURL + "/resend",
		Request: &HTTPMessage{
			Proto: "HTTP/1.1",
			HeaderFields: []HTTPHeaderField{
				{Name: "Host", Value: "old.test"},
				{Name: "X-A", Value: "first"},
				{Name: "X-B", Value: "middle"},
				{Name: "X-A", Value: "last"},
			},
		},
	}

	result, err := svc.ResendRequestWithTrafficEntry(
		context.Background(),
		ResendConfig{Count: 1},
		entry,
		nil,
	)
	if err != nil {
		t.Fatal(err)
	}
	if result != (ResendResult{Success: 1}) {
		t.Fatalf("result = %+v, want one success", result)
	}
	want := []string{
		"Host: " + strings.TrimPrefix(serverURL, "http://"),
		"X-A: first",
		"X-B: middle",
		"X-A: last",
	}
	if got := requestHeaderLines(<-wireCh); !reflect.DeepEqual(got, want) {
		t.Fatalf("resent HTTP/1 fields:\n got %#v\nwant %#v", got, want)
	}
}

func TestResendRequestRegeneratesHTTP2PseudoHeadersAndOrder(t *testing.T) {
	requestBlocks := make(chan []http.HeaderBlock, 1)
	server := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestBlocks <- http.RequestHeaderBlocks(r)
		w.WriteHeader(http.StatusNoContent)
	}))
	server.EnableHTTP2 = true
	server.StartTLS()
	defer server.Close()

	svc := newTestProxyService(t, &settingservice.ProxyConfig{SkipVerifyTLS: true})
	entry := &TrafficEntry{
		ID:     302,
		Type:   "https",
		Method: http.MethodGet,
		URL:    server.URL + "/resend?q=1",
		Request: &HTTPMessage{
			Proto: "HTTP/2.0",
			HeaderFields: []HTTPHeaderField{
				{Name: ":method", Value: "POST"},
				{Name: ":authority", Value: "old.test"},
				{Name: ":scheme", Value: "http"},
				{Name: ":path", Value: "/old"},
				{Name: "x-a", Value: "first"},
				{Name: "x-b", Value: "middle"},
				{Name: "x-a", Value: "last"},
			},
		},
	}

	result, err := svc.ResendRequestWithTrafficEntry(
		context.Background(),
		ResendConfig{Count: 1},
		entry,
		nil,
	)
	if err != nil {
		t.Fatal(err)
	}
	if result != (ResendResult{Success: 1}) {
		t.Fatalf("result = %+v, want one success", result)
	}
	blocks := <-requestBlocks
	if len(blocks) == 0 {
		t.Fatal("server captured no HTTP/2 request HeaderBlock")
	}
	want := []http.HeaderField{
		{Name: ":method", Value: "GET"},
		{Name: ":authority", Value: strings.TrimPrefix(server.URL, "https://")},
		{Name: ":scheme", Value: "https"},
		{Name: ":path", Value: "/resend?q=1"},
		{Name: "x-a", Value: "first"},
		{Name: "x-b", Value: "middle"},
		{Name: "x-a", Value: "last"},
	}
	if !reflect.DeepEqual(blocks[0].Fields, want) {
		t.Fatalf("resent HTTP/2 fields:\n got %#v\nwant %#v", blocks[0].Fields, want)
	}
}

func startRawHTTP1CaptureServer(t *testing.T, response string) (string, <-chan string) {
	t.Helper()
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = listener.Close() })
	wireCh := make(chan string, 1)
	go func() {
		conn, acceptErr := listener.Accept()
		if acceptErr != nil {
			return
		}
		defer conn.Close()
		_ = conn.SetDeadline(time.Now().Add(5 * time.Second))
		reader := bufio.NewReader(conn)
		var wire strings.Builder
		for {
			line, readErr := reader.ReadString('\n')
			if readErr != nil {
				return
			}
			wire.WriteString(line)
			if line == "\r\n" {
				break
			}
		}
		wireCh <- wire.String()
		_, _ = io.WriteString(conn, response)
	}()
	return "http://" + listener.Addr().String(), wireCh
}

func requestHeaderLines(wire string) []string {
	lines := strings.Split(wire, "\r\n")
	if len(lines) <= 2 {
		return nil
	}
	return lines[1 : len(lines)-2]
}
