package proxyservice

import (
	"context"
	"errors"
	"net/url"
	"reflect"
	"strings"
	"testing"
	"time"

	settingservice "github.com/josexy/flowlens/backend/services/setting_service"
	"github.com/josexy/websocket"
	http "github.com/josexy/xhttp"
	"github.com/josexy/xhttp/httptest"
)

type webSocketHandshakeDeadlineContext struct {
	context.Context
	deadline time.Time
}

func (ctx webSocketHandshakeDeadlineContext) Deadline() (time.Time, bool) {
	return ctx.deadline, true
}

func TestNormalizeWebSocketMessageBinaryUsesBase64(t *testing.T) {
	t.Parallel()

	msg := normalizeWebSocketMessage("receive", "binary", []byte{0x00, 0x41, 0xff})

	if msg.Direction != "receive" {
		t.Fatalf("direction = %q, want receive", msg.Direction)
	}
	if msg.MsgType != "binary" {
		t.Fatalf("msgType = %q, want binary", msg.MsgType)
	}
	if msg.Data != "AEH/" {
		t.Fatalf("data = %q, want AEH/", msg.Data)
	}
	if msg.DataSize != 3 {
		t.Fatalf("data size = %d, want 3", msg.DataSize)
	}
}

func TestNormalizeWebSocketMessageNormalizesCapturedBinaryFrames(t *testing.T) {
	t.Parallel()

	msg := normalizeWebSocketMessage("Receive", formatWebsocketMsgType(websocket.BinaryMessage), []byte{0x00, 0x41, 0xff})

	if msg.Direction != "receive" {
		t.Fatalf("expected lowercase receive direction, got %q", msg.Direction)
	}
	if msg.MsgType != "binary" {
		t.Fatalf("expected binary type, got %q", msg.MsgType)
	}
	if msg.Data != "AEH/" {
		t.Fatalf("unexpected encoded payload: %q", msg.Data)
	}
}

func TestShouldStoreWebSocketMessageMarksTruncatedWhenLimitReached(t *testing.T) {
	svc := newTestProxyService(t, nil)
	if err := svc.settingService.Update(&settingservice.Settings{
		ProxyConfig: &settingservice.ProxyConfig{},
		CacheConfig: &settingservice.CacheConfig{
			BodyCacheThresholdBytes: 1024,
			MaxWsMessages:           1,
		},
	}); err != nil {
		t.Fatalf("update settings: %v", err)
	}
	wsMsgs := &TrafficWsMsgs{
		liveState: 1,
		Messages: []*WebSocketMessage{
			{Direction: "receive", MsgType: "text", Data: "first", DataSize: 5},
		},
	}

	if svc.shouldStoreWebSocketMessage(1, wsMsgs) {
		t.Fatal("full websocket capture should not store another message")
	}
	if !wsMsgs.Truncated {
		t.Fatal("full websocket capture should be marked truncated")
	}
	if len(wsMsgs.Messages) != 1 {
		t.Fatalf("messages length = %d, want 1", len(wsMsgs.Messages))
	}
}

func TestFormatWebSocketLogTargetStripsSensitiveURLParts(t *testing.T) {
	t.Parallel()

	parsedURL, err := url.Parse("wss://user:pass@example.com/socket?token=secret#fragment")
	if err != nil {
		t.Fatalf("parse url: %v", err)
	}

	target := formatWebSocketLogTarget(parsedURL)

	if target != "wss://example.com/socket" {
		t.Fatalf("target = %q, want wss://example.com/socket", target)
	}
}

func TestBuildWebSocketHeadersPreservesOrderedFieldSemantics(t *testing.T) {
	t.Parallel()

	headers, order, err := buildWebSocketHeaders(
		[]HTTPHeaderField{
			{Name: " X-Request-Last ", Value: "last-1"},
			{Name: "X-Request-Last", Value: "last-2"},
			{Name: "x-request-first", Value: "first"},
			{Name: "Connection", Value: "close"},
			{Name: "", Value: "ignored"},
		},
	)
	if err != nil {
		t.Fatal(err)
	}

	wantHeaders := http.Header{
		"X-Request-Last":  {"last-1", "last-2"},
		"x-request-first": {"first"},
	}
	if !reflect.DeepEqual(headers, wantHeaders) {
		t.Fatalf("headers:\n got %#v\nwant %#v", headers, wantHeaders)
	}
	wantOrder := []string{
		"Host",
		"Upgrade",
		"Connection",
		"Sec-WebSocket-Key",
		"Sec-WebSocket-Version",
		"X-Request-Last",
		"x-request-first",
	}
	if !reflect.DeepEqual(order.Headers, wantOrder) {
		t.Fatalf("header order = %#v, want %#v", order.Headers, wantOrder)
	}
}

func TestBuildWebSocketHeadersRejectsUnsafeOrUnrepresentableFields(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		fields []HTTPHeaderField
		want   string
	}{
		{
			name: "pseudo header",
			fields: []HTTPHeaderField{
				{Name: ":status", Value: "200"},
			},
			want: "generated by the backend",
		},
		{
			name: "invalid token name",
			fields: []HTTPHeaderField{
				{Name: "Bad Header", Value: "value"},
			},
			want: "invalid HTTP header name",
		},
		{
			name: "invalid value",
			fields: []HTTPHeaderField{
				{Name: "X-Test", Value: "one\r\ntwo"},
			},
			want: "invalid value",
		},
		{
			name: "interleaved occurrences",
			fields: []HTTPHeaderField{
				{Name: "X-A", Value: "first"},
				{Name: "X-B", Value: "middle"},
				{Name: "X-A", Value: "last"},
			},
			want: "cannot preserve interleaved",
		},
		{
			name: "per occurrence casing",
			fields: []HTTPHeaderField{
				{Name: "X-A", Value: "first"},
				{Name: "x-a", Value: "last"},
			},
			want: "cannot preserve per-occurrence casing",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, _, err := buildWebSocketHeaders(tt.fields)
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("error = %v, want substring %q", err, tt.want)
			}
		})
	}
}

func TestWebSocketSessionPreservesHandshakeHeaderFields(t *testing.T) {
	requestFieldsCh := make(chan []HTTPHeaderField, 1)
	serverErrCh := make(chan error, 1)
	responseOrder := []string{
		"X-Response-Last",
		"sec-websocket-accept",
		"upgrade",
		"connection",
		"x-response-first",
	}
	upgrader := websocket.Upgrader{
		ResponseHeaderOrder: http.HeaderOrder{Headers: responseOrder},
	}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fields, _ := initialHeaderFields(http.RequestHeaderBlocks(r))
		requestFieldsCh <- fields
		conn, err := upgrader.Upgrade(w, r, http.Header{
			"X-Response-Last":  {"last"},
			"x-response-first": {"first"},
		})
		if err != nil {
			serverErrCh <- err
			return
		}
		defer conn.Close()
		for {
			if _, _, err := conn.ReadMessage(); err != nil {
				serverErrCh <- nil
				return
			}
		}
	}))
	defer server.Close()

	svc := newTestProxyService(t, nil)
	connectResp, err := svc.ConnectWebSocket(context.Background(), WebSocketConnectRequest{
		URL: strings.Replace(server.URL, "http://", "ws://", 1),
		HeaderFields: []HTTPHeaderField{
			{Name: "X-Request-Last", Value: "last-1"},
			{Name: "X-Request-Last", Value: "last-2"},
			{Name: "x-request-first", Value: "first"},
			{Name: "Connection", Value: "close"},
		},
	})
	if err != nil {
		t.Fatalf("connect failed: %v", err)
	}

	requestFields := <-requestFieldsCh
	customRequestFields := make([]HTTPHeaderField, 0, 3)
	requestUserAgent := ""
	for _, field := range requestFields {
		if strings.HasPrefix(strings.ToLower(field.Name), "x-request-") {
			customRequestFields = append(customRequestFields, field)
		}
		if strings.EqualFold(field.Name, "User-Agent") {
			requestUserAgent = field.Value
		}
	}
	wantRequestFields := []HTTPHeaderField{
		{Name: "X-Request-Last", Value: "last-1"},
		{Name: "X-Request-Last", Value: "last-2"},
		{Name: "x-request-first", Value: "first"},
	}
	if !reflect.DeepEqual(customRequestFields, wantRequestFields) {
		t.Errorf("request fields:\n got %#v\nwant %#v", customRequestFields, wantRequestFields)
	}
	if requestUserAgent != UserAgentHeader {
		t.Errorf("request User-Agent = %q, want %q", requestUserAgent, UserAgentHeader)
	}
	var responseLastValue string
	for _, field := range connectResp.HeaderFields {
		if strings.EqualFold(field.Name, "X-Response-Last") {
			responseLastValue = field.Value
			break
		}
	}
	if responseLastValue != "last" {
		t.Errorf("ordered response header value = %q, want last", responseLastValue)
	}
	wantResponseNames := make([]string, len(responseOrder))
	for index, name := range responseOrder {
		wantResponseNames[index] = strings.ToLower(name)
	}
	gotResponseNames := make([]string, len(connectResp.HeaderFields))
	for index, field := range connectResp.HeaderFields {
		gotResponseNames[index] = strings.ToLower(field.Name)
	}
	if !reflect.DeepEqual(gotResponseNames, wantResponseNames) {
		t.Errorf("response header order = %#v, want %#v", gotResponseNames, wantResponseNames)
	}
	if connectResp.HeadersTruncated {
		t.Error("successful WebSocket handshake headers unexpectedly truncated")
	}

	if err := svc.DisconnectWebSocket(connectResp.SessionID); err != nil {
		t.Fatalf("disconnect failed: %v", err)
	}
	select {
	case err := <-serverErrCh:
		if err != nil {
			t.Fatalf("server WebSocket failed: %v", err)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("timed out waiting for WebSocket server to close")
	}
}

func TestWebSocketHTTPRequestSessionLifecycle(t *testing.T) {
	t.Parallel()

	upgrader := websocket.Upgrader{}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		conn, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			t.Fatalf("upgrade failed: %v", err)
		}
		defer conn.Close()

		for {
			msgType, payload, err := conn.ReadMessage()
			if err != nil {
				return
			}
			if err := conn.WriteMessage(msgType, payload); err != nil {
				t.Fatalf("write failed: %v", err)
			}
		}
	}))
	defer server.Close()

	eventCh := make(chan WebSocketSessionEvent, 8)
	svc := newTestProxyService(t, nil)
	svc.emitWebSocketSessionEventHook = func(event WebSocketSessionEvent) {
		eventCh <- event
	}

	connectCallCtx, cancelConnectCall := context.WithCancel(context.Background())
	connectResp, err := svc.ConnectWebSocket(connectCallCtx, WebSocketConnectRequest{
		URL: strings.Replace(server.URL, "http://", "ws://", 1),
	})
	if err != nil {
		t.Fatalf("connect failed: %v", err)
	}
	if connectResp.SessionID == "" {
		t.Fatal("expected session id")
	}
	if connectResp.StatusCode != http.StatusSwitchingProtocols {
		t.Fatalf("status code = %d, want %d", connectResp.StatusCode, http.StatusSwitchingProtocols)
	}
	if connectResp.Protocol == "" {
		t.Fatal("expected handshake protocol")
	}
	if len(connectResp.HeaderFields) == 0 {
		t.Fatal("expected handshake response headers")
	}
	cancelConnectCall()

	waitForRequestEvent(t, eventCh, func(event WebSocketSessionEvent) bool {
		return event.SessionID == connectResp.SessionID && event.EventType == "connected"
	})

	if err := svc.SendWebSocketMessage(WebSocketSendRequest{
		SessionID: connectResp.SessionID,
		MsgType:   "text",
		Text:      "hello",
	}); err != nil {
		t.Fatalf("send failed: %v", err)
	}

	var sendEvent, receiveEvent WebSocketSessionEvent
	for sendEvent.Message == nil || receiveEvent.Message == nil {
		event := waitForRequestEvent(t, eventCh, func(event WebSocketSessionEvent) bool {
			return event.SessionID == connectResp.SessionID &&
				event.EventType == "message" &&
				event.Message != nil
		})
		if event.Message.Direction == "send" {
			sendEvent = event
		} else if event.Message.Direction == "receive" {
			receiveEvent = event
		}
	}
	if sendEvent.Message.Data != "hello" {
		t.Fatalf("send event payload = %q, want hello", sendEvent.Message.Data)
	}
	if receiveEvent.Message.Data != "hello" {
		t.Fatalf("receive event payload = %q, want hello", receiveEvent.Message.Data)
	}

	if err := svc.DisconnectWebSocket(connectResp.SessionID); err != nil {
		t.Fatalf("disconnect failed: %v", err)
	}

	waitForRequestEvent(t, eventCh, func(event WebSocketSessionEvent) bool {
		return event.SessionID == connectResp.SessionID && event.EventType == "closed"
	})

	if _, ok := svc.webSocketSessions.Load(connectResp.SessionID); ok {
		t.Fatal("session should be removed after disconnect")
	}
}

func TestWebSocketSessionConnectCancellation(t *testing.T) {
	requestStarted := make(chan struct{})
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		close(requestStarted)
		<-r.Context().Done()
	}))
	defer server.Close()

	svc := newTestProxyService(t, nil)
	t.Cleanup(svc.baseCancel)
	callCtx, cancelCall := context.WithCancel(context.Background())
	resultCh := make(chan error, 1)
	go func() {
		_, err := svc.ConnectWebSocket(callCtx, WebSocketConnectRequest{
			URL: strings.Replace(server.URL, "http://", "ws://", 1),
		})
		resultCh <- err
	}()

	select {
	case <-requestStarted:
	case <-time.After(2 * time.Second):
		cancelCall()
		t.Fatal("timed out waiting for WebSocket session handshake")
	}
	cancelCall()

	select {
	case err := <-resultCh:
		if !errors.Is(err, context.Canceled) {
			t.Fatalf("ConnectWebSocket error = %v, want context canceled", err)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("WebSocket session handshake did not stop after cancellation")
	}

	var sessionCount int
	svc.webSocketSessions.Range(func(_, _ any) bool {
		sessionCount++
		return true
	})
	if sessionCount != 0 {
		t.Fatalf("cancelled handshake left %d WebSocket sessions", sessionCount)
	}
}

func TestWebSocketSessionHandshakeTimeout(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		<-r.Context().Done()
	}))
	defer server.Close()

	svc := newTestProxyService(t, nil)
	t.Cleanup(svc.baseCancel)
	started := time.Now()
	_, err := svc.ConnectWebSocket(context.Background(), WebSocketConnectRequest{
		URL:       strings.Replace(server.URL, "http://", "ws://", 1),
		TimeoutMs: 50,
	})
	if !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("ConnectWebSocket error = %v, want context deadline exceeded", err)
	}
	if elapsed := time.Since(started); elapsed > time.Second {
		t.Fatalf("WebSocket session handshake timeout took %s", elapsed)
	}
}

func TestNormalizeWebSocketHandshakeErrorPrefersExpiredDeadline(t *testing.T) {
	ctx := webSocketHandshakeDeadlineContext{
		Context:  context.Background(),
		deadline: time.Now().Add(-time.Millisecond),
	}
	socketTimeout := errors.New("socket deadline elapsed before context timer")

	err := normalizeWebSocketHandshakeError(ctx, socketTimeout)
	if !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("normalized handshake error = %v, want context deadline exceeded", err)
	}
}

func TestWebSocketHTTPRequestSessionRemoteCloseEmitsClosedEvent(t *testing.T) {
	t.Parallel()

	upgrader := websocket.Upgrader{}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		conn, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			t.Fatalf("upgrade failed: %v", err)
		}
		defer conn.Close()

		time.Sleep(100 * time.Millisecond)
		_ = conn.WriteMessage(
			websocket.CloseMessage,
			websocket.FormatCloseMessage(websocket.CloseGoingAway, "server closing"),
		)
	}))
	defer server.Close()

	eventCh := make(chan WebSocketSessionEvent, 8)
	svc := newTestProxyService(t, nil)
	svc.emitWebSocketSessionEventHook = func(event WebSocketSessionEvent) {
		eventCh <- event
	}

	connectResp, err := svc.ConnectWebSocket(context.Background(), WebSocketConnectRequest{
		URL: strings.Replace(server.URL, "http://", "ws://", 1),
	})
	if err != nil {
		t.Fatalf("connect failed: %v", err)
	}

	waitForRequestEvent(t, eventCh, func(event WebSocketSessionEvent) bool {
		return event.SessionID == connectResp.SessionID && event.EventType == "connected"
	})

	terminalEvent := waitForRequestEvent(t, eventCh, func(event WebSocketSessionEvent) bool {
		return event.SessionID == connectResp.SessionID &&
			(event.EventType == "closed" || event.EventType == "error")
	})
	if terminalEvent.Status != "closed" && terminalEvent.Status != "error" {
		t.Fatalf("unexpected terminal status %q", terminalEvent.Status)
	}

	if _, ok := svc.webSocketSessions.Load(connectResp.SessionID); ok {
		t.Fatal("session should be removed after remote close")
	}
}

func waitForRequestEvent(
	t *testing.T,
	eventCh <-chan WebSocketSessionEvent,
	match func(WebSocketSessionEvent) bool,
) WebSocketSessionEvent {
	t.Helper()

	timeout := time.NewTimer(3 * time.Second)
	defer timeout.Stop()

	for {
		select {
		case event := <-eventCh:
			if match(event) {
				return event
			}
		case <-timeout.C:
			t.Fatal("timed out waiting for WebSocket session event")
		}
	}
}
