// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Action {
    "version": number;
    "type": string;
    "targetURL": string;
    "hostPolicy": string;
    "headers": FieldOperation[] | null;
    "query": FieldOperation[] | null;
    "body": BodyAction;
}

export interface BodyAction {
    "mode": string;
    "text": string;
    "pattern": string;
    "replacement": string;
}

export interface Changed {
    "revision": number;
}

export interface FieldOperation {
    "operation": string;
    "name": string;
    "value": string;
}

export interface PreviewResult {
    "matched": boolean;
    "captures": string[] | null;
    "targetURL": string;
}

export interface Rule {
    "id": string;
    "name": string;
    "enabled": boolean;
    "method": string;
    "urlPattern": string;
    "action": Action;
    "createdAt": number;
    "updatedAt": number;
    "unavailableReason": string;
}

export interface State {
    "revision": number;
    "enabled": boolean;
    "rules": Rule[] | null;
}
