// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteRule(id: string, expectedRevision: number): $CancellablePromise<$models.State> {
    return $Call.ByID(613660518, id, expectedRevision);
}

export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(2958466646);
}

export function Preview(rule: $models.Rule, method: string, rawURL: string): $CancellablePromise<$models.PreviewResult> {
    return $Call.ByID(1003370621, rule, method, rawURL);
}

/**
 * PreviewBody tests an unsaved regex against sample text without loading rules,
 * changing persistent state, or sending traffic.
 */
export function PreviewBody(action: $models.BodyAction, input: string): $CancellablePromise<$models.BodyPreviewResult> {
    return $Call.ByID(2622651149, action, input);
}

export function ReorderRules(ids: string[] | null, expectedRevision: number): $CancellablePromise<$models.State> {
    return $Call.ByID(2315669445, ids, expectedRevision);
}

export function SaveRule(rule: $models.Rule, expectedRevision: number): $CancellablePromise<$models.State> {
    return $Call.ByID(1427747136, rule, expectedRevision);
}

export function SetEnabled(enabled: boolean, expectedRevision: number): $CancellablePromise<$models.State> {
    return $Call.ByID(514831954, enabled, expectedRevision);
}

export function SetRuleEnabled(id: string, enabled: boolean, expectedRevision: number): $CancellablePromise<$models.State> {
    return $Call.ByID(1710119236, id, enabled, expectedRevision);
}
