// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateFolder(parentID: string, name: string): $CancellablePromise<$models.APICollectionFolder | null> {
    return $Call.ByID(2157182810, parentID, name);
}

export function DeleteNode(id: string): $CancellablePromise<void> {
    return $Call.ByID(2587827801, id);
}

export function DeleteNodes(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4217142302, ids);
}

export function GetRequest(id: string): $CancellablePromise<$models.APICollectionRequest | null> {
    return $Call.ByID(967294815, id);
}

export function ListCollection(): $CancellablePromise<$models.APICollectionTree | null> {
    return $Call.ByID(815437042);
}

export function Load(): $CancellablePromise<void> {
    return $Call.ByID(3843136982);
}

export function MoveNode(id: string, newParentID: string): $CancellablePromise<void> {
    return $Call.ByID(109700243, id, newParentID);
}

export function RenameNode(id: string, name: string): $CancellablePromise<$models.APICollectionEntry | null> {
    return $Call.ByID(3235493596, id, name);
}

export function SaveHTTPRequest(parentID: string, name: string, request: $models.SavedHTTPRequest | null): $CancellablePromise<$models.APICollectionRequest | null> {
    return $Call.ByID(3672286652, parentID, name, request);
}

export function SaveWebSocketRequest(parentID: string, name: string, request: $models.SavedWebSocketRequest | null): $CancellablePromise<$models.APICollectionRequest | null> {
    return $Call.ByID(3737595015, parentID, name, request);
}

export function UpdateHTTPRequest(id: string, request: $models.SavedHTTPRequest | null): $CancellablePromise<$models.APICollectionRequest | null> {
    return $Call.ByID(756252720, id, request);
}

export function UpdateWebSocketRequest(id: string, request: $models.SavedWebSocketRequest | null): $CancellablePromise<$models.APICollectionRequest | null> {
    return $Call.ByID(2320970523, id, request);
}
