// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxyservice$0 from "../proxy_service/models.js";

export interface APICollectionEntry {
    "folder"?: APICollectionFolder | null;
    "request"?: APICollectionRequest | null;
}

export interface APICollectionFolder {
    "id": string;
    "name": string;
    "sortOrder": number;
    "createdAt": number;
    "updatedAt": number;
    "folders": (APICollectionFolder | null)[] | null;
    "requests": (APICollectionRequest | null)[] | null;
}

export enum APICollectionNodeType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    APICollectionNodeTypeFolder = "folder",
    APICollectionNodeTypeHTTP = "http",
    APICollectionNodeTypeWebSocket = "websocket",
};

export interface APICollectionRequest {
    "id": string;
    "type": APICollectionNodeType;
    "name": string;
    "sortOrder": number;
    "createdAt": number;
    "updatedAt": number;
    "http"?: SavedHTTPRequest | null;
    "websocket"?: SavedWebSocketRequest | null;
}

export interface APICollectionTree {
    "schemaVersion": number;
    "folders": (APICollectionFolder | null)[] | null;
}

export interface SavedFile {
    "path": string;
    "name": string;
    "size": number;
}

export interface SavedFormDataItem {
    "id": string;
    "enabled": boolean;
    "name": string;
    "itemType": string;
    "value": string;
    "file"?: SavedFile | null;
}

export interface SavedHTTPRequest {
    "method": string;
    "url": string;
    "params"?: (SavedKeyValue | null)[] | null;
    "headers"?: (SavedKeyValue | null)[] | null;
    "bodyType": string;
    "bodyText": string;
    "bodyFile"?: SavedFile | null;
    "bodyFormData"?: (SavedFormDataItem | null)[] | null;
    "bodyUrlEncoded"?: (SavedKeyValue | null)[] | null;
    "inlineScriptSource"?: string | null;
    "proxyMode": proxyservice$0.SendRequestProxyMode;
    "protocol"?: proxyservice$0.SendRequestProtocol;
    "customProxy"?: string;
    "timeoutMs": number;
    "tlsClientHelloId"?: proxyservice$0.TLSClientHelloID;
    "http2Fingerprint"?: string;
}

export interface SavedKeyValue {
    "key": string;
    "value": string;
    "enabled": boolean;
}

export interface SavedWebSocketRequest {
    "url": string;
    "params"?: (SavedKeyValue | null)[] | null;
    "headers"?: (SavedKeyValue | null)[] | null;
    "draftType": string;
    "draftText"?: string;
    "draftFile"?: SavedFile | null;
    "proxyMode": proxyservice$0.SendRequestProxyMode;
    "customProxy"?: string;
    "timeoutMs": number;
    "tlsClientHelloId"?: proxyservice$0.TLSClientHelloID;
}
