// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as pythonpluginservice$0 from "../../../../josexy/flowlens/backend/services/python_plugin_service/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "python-plugins:log": pythonpluginservice$0.PluginLogEntry;
            "python-plugins:registry": pythonpluginservice$0.RegistryEvent;
            "python-plugins:status": pythonpluginservice$0.StatusEvent;
        }
    }
}
