// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settingservice$0 from "../setting_service/models.js";

export interface HARExportRequest {
    "path": string;
    "trafficIds"?: number[] | null;
}

/**
 * HARWriteResult reports how much of an export request was represented.
 * MissingBodies counts individual request/response bodies, not traffic rows.
 */
export interface HARWriteResult {
    "exported": number;
    "skipped": number;
    "missingBodies": number;
}

export interface HTTPHeaderField {
    "name": string;
    "value": string;
}

export interface HTTPMessage {
    "proto": string;
    "headerFields": HTTPHeaderField[] | null;
    "headersTruncated"?: boolean;
    "headerOrderUnavailable"?: boolean;
    "trailerFields": HTTPHeaderField[] | null;
    "trailersTruncated"?: boolean;
    "trailerOrderUnavailable"?: boolean;
    "metrics"?: HTTPMessageMetrics | null;
}

export interface HTTPMessageMetrics {
    "startedAtMicros": number;
    "endedAtMicros": number;
    "headerSize": number;
    "bodySize": number;
    "state": HTTPMessageState;
}

export enum HTTPMessageState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    HTTPMessageStatePending = "pending",
    HTTPMessageStateCompleted = "completed",
    HTTPMessageStateFailed = "failed",
    HTTPMessageStateCanceled = "canceled",
};

export interface HTTPRequestPluginDiagnostic {
    "pluginId"?: string;
    "name"?: string;
    "phase": string;
    "code": string;
    "message": string;
}

export interface HTTPRequestPluginExecution {
    "executionId": string;
    "matchedPlugins": HTTPRequestPluginMatch[] | null;
    "invocations": HTTPRequestPluginInvocation[] | null;
    "requestDurationMicros": number;
    "responseDurationMicros": number;
    "requestTransformed": boolean;
    "responseTransformed": boolean;
    "diagnostics": HTTPRequestPluginDiagnostic[] | null;
}

export interface HTTPRequestPluginInvocation {
    "pluginId": string;
    "name": string;
    "revision": string;
    "phase": string;
    "durationMicros": number;
    "transformed": boolean;
    "outcome": string;
}

export interface HTTPRequestPluginMatch {
    "pluginId": string;
    "name": string;
    "revision": string;
}

export interface HistoryMetadata {
    "key": string;
    "alias": string;

    /**
     * Unix milliseconds timestamp
     */
    "createdAt": number;
    "total": number;
    "formatVersion": number;
}

export interface InlinePythonScript {
    "enabled": boolean;
    "source": string;
}

export interface LocalDataSize {
    "cacheBytes": number;
    "historyBytes": number;
}

export interface Metadata {
    "localSourceAddr"?: string;
    "localDestinationAddr"?: string;
    "remoteSourceAddr"?: string;
    "remoteDestinationAddr"?: string;
    "localConnectionEstablishedAt": string;
    "remoteConnectionEstablishedAt": string;
    "requestProcessedAt": string;
    "sslHandshakeCompletedAt": string;
    "tls"?: TLSState | null;
    "certificate"?: ServerCertificate | null;
    "process"?: ProcessInfo | null;
}

export interface PkixName {
    "country"?: string[] | null;
    "organization"?: string[] | null;
    "organizationalUnit"?: string[] | null;
    "locality"?: string[] | null;
    "province"?: string[] | null;
    "streetAddress"?: string[] | null;
    "postalCode"?: string[] | null;
    "serialNumber"?: string;
    "commonName"?: string;
}

export interface ProcessIconData {
    "mimeType": string;
    "dataBase64": string;
}

export interface ProcessInfo {
    "status": ProcessStatus;
    "pid"?: number;
    "displayName"?: string;
    "processName"?: string;
    "executablePath"?: string;
    "appId"?: string;
    "iconKey"?: string;
    "source"?: string;
    "identityConfidence"?: string;
    "unavailableReason"?: string;
}

export enum ProcessStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProcessStatusPending = "pending",
    ProcessStatusResolved = "resolved",
    ProcessStatusRemote = "remote",
    ProcessStatusNotFound = "not_found",
    ProcessStatusPermissionDenied = "permission_denied",
    ProcessStatusUnsupported = "unsupported",
    ProcessStatusAmbiguous = "ambiguous",
};

export interface ProxyConfigApplyResult {
    "applied": boolean;
    "restartRequired": boolean;
    "restartReasons": string[] | null;
}

export interface ProxyStatus {
    "running": boolean;
    "address": string;
    "started": string;
    "captureAlias": string;
}

export interface RawTCPTunnelInfo {
    "source": RawTCPTunnelSource;
    "hostPort": string;
    "tls": boolean;
}

export enum RawTCPTunnelSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RawTCPTunnelSourceDirect = "direct",
    RawTCPTunnelSourceHTTPConnect = "http_connect",
    RawTCPTunnelSourceSOCKS5 = "socks5",
    RawTCPTunnelSourceUnknown = "unknown",
};

export interface RequestBodyRecoveryFormDataItem {
    "enabled": boolean;
    "name": string;

    /**
     * "text" or "file"
     */
    "itemType": string;
    "value": string;
    "file"?: RequestDraftFile | null;
}

export interface RequestBodyRecoveryResult {
    "bodyType": SendRequestBodyType;
    "text": string;
    "file"?: RequestDraftFile | null;
    "formData"?: (RequestBodyRecoveryFormDataItem | null)[] | null;
    "urlEncoded"?: (SendRequestURLEncodedItem | null)[] | null;
    "warnings"?: string[] | null;
}

export interface RequestDraftFile {
    "path": string;
    "name": string;
    "size": number;
}

export interface ResendConfig {
    /**
     * delay before first request (ms)
     */
    "delayMs": number;

    /**
     * interval between requests (ms)
     */
    "intervalMs": number;

    /**
     * number of times to send
     */
    "count": number;

    /**
     * route through the running MITM proxy
     */
    "useProxy": boolean;

    /**
     * upstream proxy URL (used when UseProxy=false)
     */
    "upstreamProxy": string;
}

export interface ResendResult {
    "success": number;
    "failed": number;
}

export interface SaveBodyToFileRequest {
    "path": string;
    "body": string;
    "bodyEncoding": string;
    "contentType": string;
}

export interface SendRequestBody {
    "bodyType": SendRequestBodyType;
    "text": string;
    "file"?: SendRequestFile | null;
    "formData"?: (SendRequestFormDataItem | null)[] | null;
    "urlEncoded"?: (SendRequestURLEncodedItem | null)[] | null;
}

export enum SendRequestBodyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SendRequestBodyTypeNone = "none",
    SendRequestBodyTypeJSON = "json",
    SendRequestBodyTypeText = "text",
    SendRequestBodyTypeXML = "xml",
    SendRequestBodyTypeBinary = "binary",
    SendRequestBodyTypeFile = "file",
    SendRequestBodyTypeFormData = "form-data",
    SendRequestBodyTypeURLEncoded = "urlencoded",
};

export interface SendRequestConfig {
    /**
     * none / system / mitm / custom
     */
    "proxyMode": SendRequestProxyMode;

    /**
     * auto / http1 / http2
     */
    "protocol": SendRequestProtocol;

    /**
     * used when ProxyMode=custom
     */
    "customProxy": string;

    /**
     * <=0 means no timeout
     */
    "timeoutMs": number;
    "tlsClientHelloId": TLSClientHelloID;
    "http2Fingerprint": string;
    "disablePlugins": boolean;
    "pluginExecutionId": string;
    "inlinePythonScript"?: InlinePythonScript | null;
}

export interface SendRequestFile {
    "path": string;
    "name": string;
    "size": number;
}

export interface SendRequestFormDataItem {
    "enabled": boolean;
    "name": string;

    /**
     * "text" or "file"
     */
    "itemType": string;
    "value": string;
    "file"?: SendRequestFile | null;
    "filename"?: string;
}

export enum SendRequestProtocol {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SendRequestProtocolAuto = "auto",
    SendRequestProtocolHTTP1 = "http1",
    SendRequestProtocolHTTP2 = "http2",
};

export enum SendRequestProxyMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SendRequestProxyModeNone = "none",
    SendRequestProxyModeSystem = "system",
    SendRequestProxyModeMITM = "mitm",
    SendRequestProxyModeCustom = "custom",
};

export interface SendRequestResponse {
    "outcome": string;
    "pluginExecution"?: HTTPRequestPluginExecution | null;
    "statusCode": number;
    "statusText": string;
    "protocol": string;
    "headerFields": HTTPHeaderField[] | null;
    "headersTruncated"?: boolean;
    "headerOrderUnavailable"?: boolean;
    "trailerFields": HTTPHeaderField[] | null;
    "trailersTruncated"?: boolean;
    "trailerOrderUnavailable"?: boolean;
    "body": string;

    /**
     * "" or "base64"
     */
    "bodyEncoding": string;
    "streaming"?: boolean;
    "streamSessionId"?: string;
}

export interface SendRequestURLEncodedItem {
    "enabled": boolean;
    "name": string;
    "value": string;
}

export interface ServerCertificate {
    "version"?: number;
    "notBeforeMicros"?: number;
    "notAfterMicros"?: number;
    "subject"?: PkixName | null;
    "issuer"?: PkixName | null;
    "dnsNames"?: string[] | null;
    "ipAddresses"?: string[] | null;
    "serialNumber"?: string;
    "signatureAlgorithm"?: string;
    "sha1Fingerprint"?: string;
    "sha256Fingerprint"?: string;
}

export interface SystemProxyStatus {
    "supported": boolean;
    "modeSupported": boolean;
    "active": boolean;
    "address": string;
    "mode": settingservice$0.ProxyMode;
}

export enum TLSClientHelloID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TLSClientHelloGolang = "golang",
    TLSClientHelloChromeAuto = "chrome_auto",
    TLSClientHelloFirefoxAuto = "firefox_auto",
    TLSClientHelloSafariAuto = "safari_auto",
    TLSClientHelloEdgeAuto = "edge_auto",
    TLSClientHelloIOSAuto = "ios_auto",
    TLSClientHelloAndroid11OkHTTP = "android_11_okhttp",
    TLSClientHelloRandomizedALPN = "randomized_alpn",
};

export interface TLSState {
    "serverName"?: string;
    "supportedAlpn"?: string[] | null;
    "supportedVersion"?: string[] | null;
    "supportedCipherSuites"?: string[] | null;
    "selectedAlpn"?: string;
    "selectedVersion"?: string;
    "selectedCipherSuite"?: string;
}

export interface TrafficBodyView {
    "reqBody": string;
    "rspBody": string;

    /**
     * "" or "base64"
     */
    "reqBodyEnc"?: string;

    /**
     * "" or "base64"
     */
    "rspBodyEnc"?: string;
    "wsMsgs"?: (WebSocketMessage | null)[] | null;
    "wsMsgsTruncated"?: boolean;
}

export interface TrafficEntry {
    "id": number;

    /**
     * Revision orders the initial live snapshot and its later patch events. It
     * is runtime-only and intentionally omitted from HBIN encoding.
     */
    "revision"?: number;

    /**
     * "http", "https", "ws", "wss", "tcp"
     */
    "type": string;
    "startedAt": string;
    "method": string;
    "url": string;
    "host": string;
    "path": string;
    "statusCode": number;
    "status": string;
    "metadata"?: Metadata | null;
    "rawTcp"?: RawTCPTunnelInfo | null;
    "request"?: HTTPMessage | null;
    "response"?: HTTPMessage | null;
    "error"?: TrafficError | null;
}

export interface TrafficError {
    "timestamp": string;
    "error": string;
}

export interface TrafficStatistics {
    "total": number;
    "totalHttp": number;
    "totalWs": number;
    "totalTcp": number;
}

export interface WebSocketConnectRequest {
    "url": string;
    "headerFields": HTTPHeaderField[] | null;
    "proxyMode": SendRequestProxyMode;
    "customProxy": string;
    "timeoutMs": number;
    "tlsClientHelloId": TLSClientHelloID;
}

export interface WebSocketConnectResponse {
    "sessionId": string;
    "status": string;
    "statusCode": number;
    "statusText": string;
    "protocol": string;
    "headerFields": HTTPHeaderField[] | null;
    "headersTruncated"?: boolean;
    "headerOrderUnavailable"?: boolean;
}

export interface WebSocketMessage {
    /**
     * "send" or "receive"
     */
    "direction": string;

    /**
     * "text" or "binary"
     */
    "msgType": string;
    "data": string;
    "dataSize": number;
    "error"?: TrafficError | null;
}

export interface WebSocketSendRequest {
    "sessionId": string;

    /**
     * "text" or "binary"
     */
    "msgType": string;
    "text": string;
    "file"?: SendRequestFile | null;
}
