// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyCurrentProxyConfig(): $CancellablePromise<$models.ProxyConfigApplyResult> {
    return $Call.ByID(3714098916);
}

export function ClearCacheAndHistory(): $CancellablePromise<void> {
    return $Call.ByID(3246886421);
}

export function ClearCacheFiles(): $CancellablePromise<void> {
    return $Call.ByID(1084827885);
}

/**
 * ClearTraffic removes all stored traffic and its persisted current snapshot.
 * The disk pair is deleted before the in-memory reset so a deletion failure
 * cannot make cleared traffic reappear after a crash or restart.
 */
export function ClearTraffic(): $CancellablePromise<void> {
    return $Call.ByID(931845097);
}

export function ConnectWebSocket(req: $models.WebSocketConnectRequest): $CancellablePromise<$models.WebSocketConnectResponse> {
    return $Call.ByID(2227000346, req);
}

/**
 * DeleteTraffic deletes traffic entries
 */
export function DeleteTraffic(id: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(2185528821, id);
}

export function DisconnectHTTPRequestStream(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1747603338, sessionID);
}

export function DisconnectWebSocket(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(547919344, sessionID);
}

/**
 * ExportHAR exports all current capture entries when TrafficIDs is empty, or
 * the requested entries in the supplied order otherwise.
 */
export function ExportHAR(request: $models.HARExportRequest): $CancellablePromise<$models.HARWriteResult> {
    return $Call.ByID(999364280, request);
}

export function GetLocalDataSize(): $CancellablePromise<$models.LocalDataSize> {
    return $Call.ByID(2690234029);
}

export function GetProcessIcon(iconKey: string): $CancellablePromise<$models.ProcessIconData | null> {
    return $Call.ByID(3428577587, iconKey);
}

/**
 * GetStatistics returns current traffic statistics
 */
export function GetStatistics(): $CancellablePromise<$models.TrafficStatistics> {
    return $Call.ByID(2833468998);
}

export function GetStatus(): $CancellablePromise<$models.ProxyStatus> {
    return $Call.ByID(1417834171);
}

export function GetSystemProxyStatus(): $CancellablePromise<$models.SystemProxyStatus> {
    return $Call.ByID(4060002090);
}

/**
 * GetTraffic returns the newest frontend-sized window (without bodies). Older
 * entries remain retained for the complete history file and HAR export.
 */
export function GetTraffic(): $CancellablePromise<($models.TrafficEntry | null)[] | null> {
    return $Call.ByID(2986623626);
}

/**
 * GetTrafficBodyView returns a single entry with bodies
 */
export function GetTrafficBodyView(id: number): $CancellablePromise<$models.TrafficBodyView | null> {
    return $Call.ByID(2805500463, id);
}

export function RecoverRequestBodyForEditing(requestURL: string, headerFields: $models.HTTPHeaderField[] | null, bodyView: $models.TrafficBodyView): $CancellablePromise<$models.RequestBodyRecoveryResult> {
    return $Call.ByID(3243491271, requestURL, headerFields, bodyView);
}

export function ResendRequest(id: number, cfg: $models.ResendConfig): $CancellablePromise<$models.ResendResult> {
    return $Call.ByID(2207703317, id, cfg);
}

export function ResolveRequestDraftFile(path: string): $CancellablePromise<$models.RequestDraftFile | null> {
    return $Call.ByID(3987633355, path);
}

export function RestartCapture(saveCurrent: boolean): $CancellablePromise<void> {
    return $Call.ByID(1269165668, saveCurrent);
}

export function SaveBodyToFile(req: $models.SaveBodyToFileRequest): $CancellablePromise<void> {
    return $Call.ByID(263095725, req);
}

export function SendHTTPRequest(cfg: $models.SendRequestConfig, method: string, targetURL: string, headerFields: $models.HTTPHeaderField[] | null, body: $models.SendRequestBody): $CancellablePromise<$models.SendRequestResponse> {
    return $Call.ByID(2407609822, cfg, method, targetURL, headerFields, body);
}

export function SendWebSocketMessage(req: $models.WebSocketSendRequest): $CancellablePromise<void> {
    return $Call.ByID(4236216371, req);
}

/**
 * SetLiveTrafficDetail selects the only traffic entry whose live body or
 * WebSocket updates should be delivered to the frontend. ID zero disables it.
 */
export function SetLiveTrafficDetail(id: number): $CancellablePromise<void> {
    return $Call.ByID(1034534781, id);
}

export function SetSystemProxyEnabled(enabled: boolean): $CancellablePromise<$models.SystemProxyStatus> {
    return $Call.ByID(1733824733, enabled);
}

export function Start(): $CancellablePromise<$models.ProxyStatus> {
    return $Call.ByID(2734287349);
}

export function Stop(): $CancellablePromise<$models.ProxyStatus> {
    return $Call.ByID(1877241863);
}

export function UpdateHistoryAlias(alias: string): $CancellablePromise<void> {
    return $Call.ByID(1224368706, alias);
}
