// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CreatePluginInput {
    "id": string;
    "name": string;
    "description": string;
    "paramsJson": string;
}

export interface CreateRuleInput {
    "id": string;
    "enabled": boolean;
    "method": string;
    "urlPattern": string;
}

export interface InterpreterCandidate {
    "interpreterPath": string;
    "pythonMajor": number;
    "pythonMinor": number;
    "pythonPatch": number;
    "implementation": string;
    "current": boolean;
}

export interface ManagedPluginFile {
    "path": string;
    "content": string;
}

export interface Plugin {
    "id": string;
    "name": string;
    "description": string;
    "enabled": boolean;
    "sortOrder": number;
    "paramsJson": string;
    "activeRevision": string;
    "lastGoodRevision": string;
    "validationStatus": ValidationStatus;
    "validationError": string;
    "createdAt": number;
    "updatedAt": number;
    "rules": (Rule | null)[] | null;
}

export interface PluginLogEntry {
    "eventId": number;
    "requestId": string;
    "executionId": string;
    "pluginId": string;
    "level": string;
    "stream": string;
    "message": string;
    "timestamp": number;
}

export interface RegistryEvent {
    "eventId": number;
    "change": string;
    "pluginId"?: string;
}

export interface Rule {
    "id": string;
    "pluginId": string;
    "enabled": boolean;
    "method": string;
    "urlPattern": string;
    "sortOrder": number;
    "createdAt": number;
    "updatedAt": number;
}

export interface RuntimeStatus {
    "enabled": boolean;
    "interpreterPath": string;
    "hookTimeoutMs": number;
    "ready": boolean;
    "workerCount": number;
    "protocolVersion": number;
    "sdkApiVersion": number;
    "pythonMajor": number;
    "pythonMinor": number;
    "pythonPatch": number;
    "implementation": string;
    "error": string;
}

export interface StatusEvent {
    "eventId": number;
    "status": RuntimeStatus;
}

export interface UpdatePluginInput {
    "name": string;
    "description": string;
    "paramsJson": string;
}

export interface UpdateRuleInput {
    "enabled": boolean;
    "method": string;
    "urlPattern": string;
}

export enum ValidationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ValidationStatusUnavailable = "unavailable",
    ValidationStatusValid = "valid",
    ValidationStatusInvalid = "invalid",
};
