// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settingservice$0 from "../setting_service/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ConfigureRuntime(config: settingservice$0.PythonPluginConfig): $CancellablePromise<$models.RuntimeStatus | null> {
    return $Call.ByID(2013482198, config);
}

export function CreatePlugin(input: $models.CreatePluginInput): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(4253573973, input);
}

export function CreateRule(pluginID: string, input: $models.CreateRuleInput): $CancellablePromise<$models.Rule | null> {
    return $Call.ByID(2627800188, pluginID, input);
}

export function DeletePlugin(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(2804729870, pluginID);
}

export function DeletePluginFile(pluginID: string, relativePath: string): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(3656025128, pluginID, relativePath);
}

export function DeleteRule(pluginID: string, ruleID: string): $CancellablePromise<void> {
    return $Call.ByID(824463455, pluginID, ruleID);
}

export function DiscoverInterpreters(configuredPath: string): $CancellablePromise<$models.InterpreterCandidate[] | null> {
    return $Call.ByID(2125088966, configuredPath);
}

export function GetPlugin(pluginID: string): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(1710558565, pluginID);
}

export function GetRuntimeConfig(): $CancellablePromise<settingservice$0.PythonPluginConfig | null> {
    return $Call.ByID(1868989756);
}

export function GetRuntimeStatus(): $CancellablePromise<$models.RuntimeStatus | null> {
    return $Call.ByID(1816771548);
}

export function ListPluginFiles(pluginID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3152776624, pluginID);
}

export function ListPlugins(): $CancellablePromise<($models.Plugin | null)[] | null> {
    return $Call.ByID(3410006018);
}

export function OpenPluginDirectory(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(834876308, pluginID);
}

export function OpenPluginsDirectory(): $CancellablePromise<void> {
    return $Call.ByID(2610388805);
}

export function ReadPluginFile(pluginID: string, relativePath: string): $CancellablePromise<$models.ManagedPluginFile | null> {
    return $Call.ByID(543006855, pluginID, relativePath);
}

export function ReloadPlugin(pluginID: string): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(494693736, pluginID);
}

export function ReloadRuntime(): $CancellablePromise<$models.RuntimeStatus | null> {
    return $Call.ByID(2012431941);
}

export function RenamePluginFile(pluginID: string, oldRelativePath: string, newRelativePath: string): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(3028162181, pluginID, oldRelativePath, newRelativePath);
}

export function ReorderPlugins(pluginIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2037833227, pluginIDs);
}

export function ReorderRules(pluginID: string, ruleIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2970260928, pluginID, ruleIDs);
}

export function SetPluginEnabled(pluginID: string, enabled: boolean): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(1534536378, pluginID, enabled);
}

export function TestInterpreter(interpreterPath: string): $CancellablePromise<$models.RuntimeStatus | null> {
    return $Call.ByID(590587312, interpreterPath);
}

export function UpdatePlugin(pluginID: string, input: $models.UpdatePluginInput): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(3535156556, pluginID, input);
}

export function UpdatePluginParams(pluginID: string, paramsJSON: string): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(3907091226, pluginID, paramsJSON);
}

export function UpdateRule(pluginID: string, ruleID: string, input: $models.UpdateRuleInput): $CancellablePromise<$models.Rule | null> {
    return $Call.ByID(957530985, pluginID, ruleID, input);
}

export function ValidatePlugin(pluginID: string): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(936262867, pluginID);
}

export function WritePluginFile(pluginID: string, relativePath: string, content: string): $CancellablePromise<$models.Plugin | null> {
    return $Call.ByID(3281531928, pluginID, relativePath, content);
}
