// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogLevelTrace = "trace",
    LogLevelDebug = "debug",
    LogLevelInfo = "info",
    LogLevelWarn = "warn",
    LogLevelError = "error",
};

export interface LogStatus {
    "enabled": boolean;
    "level": LogLevel;
    "logDir": string;
    "currentFile": string;
    "maxSizeBytes": number;
    "maxBackups": number;
    "console": boolean;
    "debugMode": boolean;
}
