// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MemStatsService exposes Go runtime memory monitoring to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetMemStats returns a one-time snapshot without affecting monitoring state.
 */
export function GetMemStats(): $CancellablePromise<$models.MemSnapshot> {
    return $Call.ByID(2419864308);
}

/**
 * GetMonitoringStatus returns current monitoring state.
 */
export function GetMonitoringStatus(): $CancellablePromise<$models.MonitoringStatus> {
    return $Call.ByID(1313356192);
}

/**
 * StartMonitoring starts (or restarts with new interval) the monitoring goroutine.
 * intervalMs is clamped to a minimum of 100ms.
 */
export function StartMonitoring(intervalMs: number): $CancellablePromise<void> {
    return $Call.ByID(3090426974, intervalMs);
}

/**
 * StopMonitoring stops the monitoring goroutine.
 */
export function StopMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(1735014482);
}
