// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MemSnapshot holds a point-in-time snapshot of Go runtime memory statistics.
 */
export interface MemSnapshot {
    /**
     * Unix milliseconds
     */
    "timestamp": number;
    "goVersion": string;
    "goos": string;
    "goarch": string;
    "numGoroutine": number;
    "numCPU": number;

    /**
     * Heap
     */
    "heapAlloc": number;
    "heapSys": number;
    "heapInuse": number;
    "heapIdle": number;
    "heapReleased": number;
    "heapObjects": number;

    /**
     * Stack
     */
    "stackInuse": number;
    "stackSys": number;

    /**
     * Overall
     */
    "sys": number;
    "alloc": number;
    "totalAlloc": number;
    "mallocs": number;
    "frees": number;

    /**
     * GC
     */
    "numGC": number;
    "numForcedGC": number;
    "gcCPUFraction": number;
    "pauseTotalNs": number;

    /**
     * last GC pause
     */
    "pauseNs": number;
    "nextGC": number;

    /**
     * Unix ms; 0 if no GC yet
     */
    "lastGC": number;

    /**
     * Other system memory
     */
    "gcSys": number;
    "mspanSys": number;
    "mcacheSys": number;
    "otherSys": number;
}

/**
 * MonitoringStatus describes the current state of memory monitoring.
 */
export interface MonitoringStatus {
    "monitoring": boolean;
    "intervalMs": number;
}
