// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetEnvironmentInfo returns build environment details for the running application.
 */
export function GetEnvironmentInfo(): $CancellablePromise<$models.EnvironmentInfo> {
    return $Call.ByID(1660576066);
}

/**
 * WindowClose closes the window
 */
export function WindowClose(): $CancellablePromise<void> {
    return $Call.ByID(1213587529);
}

/**
 * WindowIsMaximized returns whether the window is maximized
 */
export function WindowIsMaximized(): $CancellablePromise<boolean> {
    return $Call.ByID(1380106131);
}

/**
 * WindowMaximize toggles window maximize/unmaximize
 */
export function WindowMaximize(): $CancellablePromise<void> {
    return $Call.ByID(3048707673);
}

/**
 * WindowMinimize minimizes the window
 */
export function WindowMinimize(): $CancellablePromise<void> {
    return $Call.ByID(3321887299);
}
