// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CanSelfUpdate reports whether the running installation can be replaced by
 * the built-in updater.
 */
export function CanSelfUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(3323249888);
}

/**
 * CancelUpdate cancels the active check or download and waits for cleanup.
 */
export function CancelUpdate(): $CancellablePromise<void> {
    return $Call.ByID(137014300);
}

/**
 * CheckForUpdates starts a check without opening the framework updater UI.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(4204358798);
}

/**
 * DownloadUpdate downloads, verifies, and stages the release found by the
 * latest successful check.
 */
export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3931171182);
}

/**
 * GetEnvironmentInfo returns build environment details for the running application.
 */
export function GetEnvironmentInfo(): $CancellablePromise<$models.EnvironmentInfo> {
    return $Call.ByID(1660576066);
}

/**
 * GetUpdateSnapshot returns the authoritative state used by every window.
 */
export function GetUpdateSnapshot(): $CancellablePromise<$models.UpdateSnapshot> {
    return $Call.ByID(3358282592);
}

/**
 * RestartForUpdate requests the application's guarded restart flow, including
 * the unsaved-settings confirmation, even if the update window was closed.
 */
export function RestartForUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3631527152);
}

/**
 * WindowClose closes the window
 */
export function WindowClose(): $CancellablePromise<void> {
    return $Call.ByID(1213587529);
}

/**
 * WindowIsMaximized returns whether the window is maximized
 */
export function WindowIsMaximized(): $CancellablePromise<boolean> {
    return $Call.ByID(1380106131);
}

/**
 * WindowMaximize toggles window maximize/unmaximize
 */
export function WindowMaximize(): $CancellablePromise<void> {
    return $Call.ByID(3048707673);
}

/**
 * WindowMinimize minimizes the window
 */
export function WindowMinimize(): $CancellablePromise<void> {
    return $Call.ByID(3321887299);
}
