// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentInfo describes the build and runtime environment used by the running application.
 */
export interface EnvironmentInfo {
    "appVersion": string;
    "goVersion": string;
    "wailsVersion": string;
    "buildCommit": string;
    "goos": string;
    "goarch": string;
}
