// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logger$0 from "../../pkg/logger/models.js";

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(4114798015);
}

export function GetLogStatus(): $CancellablePromise<logger$0.LogStatus | null> {
    return $Call.ByID(1075777891);
}

export function OpenLogDir(): $CancellablePromise<void> {
    return $Call.ByID(2603518374);
}

export function SetLogEnabled(enabled: boolean): $CancellablePromise<logger$0.LogStatus | null> {
    return $Call.ByID(1644679598, enabled);
}

export function SetLogLevel(level: logger$0.LogLevel): $CancellablePromise<logger$0.LogStatus | null> {
    return $Call.ByID(2742443661, level);
}
