// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ShortcutService from "./shortcutservice.js";
export {
    ShortcutService
};

export {
    ShortcutRuntimeStatus
} from "./models.js";

export type {
    ShortcutApplyResult,
    ShortcutCommandRuntimeState,
    ShortcutRuntimeState
} from "./models.js";
