// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settingservice$0 from "../setting_service/models.js";

export interface ShortcutApplyResult {
    "applied": boolean;

    /**
     * Config is always the effective configuration after the attempt. On a
     * rejected or rolled-back rebind it is the restored previous configuration.
     */
    "config": settingservice$0.ShortcutConfig | null;
    "runtimeState": ShortcutRuntimeState;
    "warnings": string[] | null;
    "errorCode"?: string;
    "errorMessage"?: string;
}

export interface ShortcutCommandRuntimeState {
    "status": ShortcutRuntimeStatus;
    "accelerator"?: string;
}

export interface ShortcutRuntimeState {
    "commands": { [_ in string]?: ShortcutCommandRuntimeState } | null;
    "warnings": string[] | null;
}

export enum ShortcutRuntimeStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShortcutStatusActive = "active",
    ShortcutStatusConflict = "conflict",
    ShortcutStatusUnsupported = "unsupported",
    ShortcutStatusPortalPending = "portalPending",
};
