// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settingservice$0 from "../setting_service/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyShortcutConfig(config: settingservice$0.ShortcutConfig | null): $CancellablePromise<$models.ShortcutApplyResult | null> {
    return $Call.ByID(1560695553, config);
}

export function GetShortcutRuntimeState(): $CancellablePromise<$models.ShortcutRuntimeState> {
    return $Call.ByID(4225386654);
}
